### ISSUE TITLE
Suggestion: Implement better documentation

### ISSUE THREAD

**Issue by yndrelbosch** [pacollins/hugo-future-imperfect-slim#1]
yes

yes

There is no such wiki

yes

## Expected Behavior

Include better documentation, including these shortcodes that the theme supposedly includes, but are not listed anywhere.

## Current Behavior

The current documentation is limited and does not list the shortcodes that supposedly ship with this theme.

## Possible Solution

Actually using the  provided Wiki would be a good method of implementing better documentation.

## Steps to Reproduce or Template with Error (for bugs)

1.
2.
3.
4.

## Context

I cannot make full and proper use of this theme if I don't know all the ins and outs of it.

**Comment by pacollins** [comment]
Good afternoon!

Documentation is the next step, but the theme has been rebased. Hopefully you will find that the config.toml is well documented with inline comments.

The only additional short code at the moment is fancybox, which the details are outlined within the [short code here](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/shortcodes/fancybox.html).

There are a few more points of functionality that I would like to finalize before spending the time documenting everything.

If you have questions about a specific feature, feel free to ask.

**Comment by pacollins** [comment]
Update: I have added a [new blog post](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/exampleSite/content/blog/examples.md) to the example site that shows you all markdown and use of the fancybox shortcode. Not a perfect fix, but an improvement. It should go on the live site soon (not sure of their update schedule).
