### ISSUE TITLE
BUG: categories not performance good

### ISSUE THREAD

**Issue by yhyddr** [pacollins/hugo-future-imperfect-slim#10]
# Bug Report
## Describe the bug
categories be a blog page

## To Reproduce
hugo server
localhost:1313/categories/
and didn't see the categories list

## Expected behavior
a categories list

##Screenshots
![image](https://user-images.githubusercontent.com/32089134/58222586-1df21600-7d49-11e9-933b-2697ffcbe7b2.png)

## Environment
 - **Hugo Version:** [ 0.55.6]
 - **Browser and Version:** [e.g. Chrome 74.0.3729.108]
 - **Platform:** [ Desktop and Mobile]
 - **Link to Project: **

## Additional context

I also use tags for that ,and tags performance good.
![image](https://user-images.githubusercontent.com/32089134/58222701-7cb78f80-7d49-11e9-8835-402655fa89bf.png)

**Comment by pacollins** [comment]
I did some quick tests and was not able to find the reason for this bug as of right now. I will look into it further this weekend.

**Comment by yhyddr** [comment]
I think it's my fault? when I then generate both on categories and tags,It's magic that only categories seems good,tags page went wrong this time .

I think a post can't not add categories and tags at once? I'm sorry to report this to waste your time

**Comment by pacollins** [comment]
You are fine. I don't think it is your fault. My understanding is that you
can have both, I just wasn't able to find the fix quick.

I will keep looking this weekend.
