### ISSUE TITLE
FEATURE: Remove About from the Sidebar

### ISSUE THREAD

**Issue by eribean** [pacollins/hugo-future-imperfect-slim#100]
# Feature Request
Remove "about" from the sidebar
Changing categories to false under [params.sidebar] removes it from the landing page, however the same is not true for about.  

## Is your feature request related to a problem?

No

## Solution

A parameter that toggles sidebar "About" similar to categories.

**Comment by pacollins** [comment]
Just as a heads up, both of the main maintainers of this theme just got back to work this fall and are swamped. We are still facilitating PRs from contributors, but our personal contributions are slim at the moment.

**Comment by eribean** [comment]
Thank you, appreciate it!
