### ISSUE TITLE
BUG: css won't allow changing color of mini-posts textbox in sidebar

### ISSUE THREAD

**Issue by samiaab1990** [pacollins/hugo-future-imperfect-slim#101]
# Bug Report
## Describe the bug
Hi there.
I created a website using this template and have a add-on css overwriting the original css configurations. I could not get the background color (originally #FFFFF in main.scss) to change for each item in the sidebar recent posts container. I would like to know how to change the mini-post items to go along with the rest of my webpage color 

I will attach the code below and the exact modification I'm seeking:

code:

 #recent-posts {
   display: flex;
   flex-wrap: wrap;
   justify-content: space-between;
   > header {
     flex: 1 1 100%;
   }
   **_.mini-post {
     background: transparent;_**
     border: solid 1px rgba(160, 160, 160, 0.3);
 display: flex;
 flex-direction: column;
     margin-bottom: 1em;
     width: 100%;
     @include for-laptop-up {
       width: 49%;
     }
     @include for-desktop-up {
       width: 100%;
     }
     header {
       min-height: 4em;
       padding: 1.25em 1.25em 0.1em 1.25em;
       position: relative;
       @include for-laptop-up {
         border-top: solid 1px rgba(160,160,160,0.3);
       }
       @include for-desktop-up {
         border: 0;
       }
       h1 {
         font-size: 0.7em;
       }
       .published {
         display: block;
         font-family: "Raleway", Helvetica, sans-serif;
         font-size: 0.6em;
         font-weight: 400;
         letter-spacing: 0.25em;
         margin: -0.625em 0 1.7em 0;
         text-transform: uppercase;
       }
       .author, .format {
         position: absolute;
         right: 2em;
         top: 2em;
       }
     }
     section {
       flex-grow: 1;
       overflow: hidden;
       .image {
         &:hover {
           img {
             -moz-transform: scale(1.05);
             -webkit-transform: scale(1.05);
             -ms-transform: scale(1.05);
             transform: scale(1.05);
           }
         }
         img {
           display: block;
           height: 100%;
           margin: 0;
           -moz-transition: -moz-transform 0.2s ease-out;
           -webkit-transition: -webkit-transform 0.2s ease-out;
           -ms-transition: -ms-transform 0.2s ease-out;
           transition: transform 0.2s ease-out;
           width: 100%;
         }
       }
     }
   }
 }

<img width="244" alt="screenshot_of_minipost" src="https://user-images.githubusercontent.com/39127633/68079541-b513cd00-fdc1-11e9-8a91-c3d4c1e29ff9.png">

**Comment by pacollins** [comment]
See #87

**Comment by samiaab1990** [comment]
I figured it out what the problem was with this-I will close this and continue to update from the pull request I made
