### ISSUE TITLE
BUG: Languages side bar won't collapse

### ISSUE THREAD

**Issue by CJAP** [pacollins/hugo-future-imperfect-slim#103]
# Bug Report
## Languages side bar won't collapse
When viewing the demo and/or downloading the files, the languages side bar always stays visible and out through half the web page. It still changes the languages, but does not collapse into the right side of the page when language has been selected.

## To Reproduce
Go to 'https://themes.gohugo.io/theme/hugo-future-imperfect-slim/

## Expected behavior
Before and after selecting the language of choice, only the current language should show up on the top right corner. The menu itself should collapse to the right after a selection is made.

**Comment by pacollins** [comment]
The issue seems to be a missing `display: flex` on `#lang-menu.flyout-menu a`. I am not sure of the exact spot it should be or where it got removed from (possibly with the flag removal #61).

I should be able to patch this later today.

**Comment by pacollins** [comment]
I can't seem to reproduce this locally and might be an issue with the theme site cache.

@VincentTam - Do you have this error on localhost?

**Comment by pacollins** [comment]
@CJAP - I know it has been a while, but I was never able to reproduce it locally. I see it on the themes site, but without being able to reproduce it locally I can't solve the problem.

**Comment by pacollins** [comment]
I believe it was an issue with not updating the assets. https://github.com/pacollins/hugo-future-imperfect-slim/commit/047d61748520cd78186a14a158e23798ec717903
