### ISSUE TITLE
BUG: Table alignment is not correct.

### ISSUE THREAD

**Issue by javydekoning** [pacollins/hugo-future-imperfect-slim#106]
# Bug Report

Rendering of Markdown tables is not correct.

## Describe the bug

Alignment of columns does not correctly render. See the example below 

## To Reproduce

Launch the example site and navigate to http://localhost:1313/blog/examples/ 

You'll find this table:

```
Colons can be used to align columns.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

## Expected behavior

Table's should correctly align according to colons.

## Screenshots

![screenshot](https://i.imgur.com/KS3I11c.png)

## Environment

 - **Hugo Version:** Hugo Static Site Generator v0.61.0/extended darwin/amd64
 - **Browser and Version:** Both latest versions of Chrome and Firefox
 - **Platform:** MacOS
 - **Link to Project:** N/A

**Comment by javydekoning** [comment]
I tried to workaround this by loading a customer css. In my config file like this

```toml
  cssFiles              = ["default","/css/highlight.css","/css/table.css"]
```

 I used a bootstrap base table.css  [source](https://www.mybluelinux.com/css/bootstrap-table.css) and created a shortcode in `/layouts/shortcodes`

```
{{ $htmlTable := .Inner | markdownify }}
{{ $class := .Get 0 }}
{{ $old := "<table>" }}
{{ $new := printf "<table class=\"%s\">" $class }}
{{ $htmlTable := replace $htmlTable $old $new }}
{{ $htmlTable | safeHTML }}
```

Unfortunately this only partially works as it likely interferes with the existing css.

**Comment by pacollins** [comment]
Have you tried without loading the site css to see if it is working right?

**Comment by javydekoning** [comment]
yeah, without the theme css it works:

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

![native](https://i.imgur.com/gqYbyjT.png)
![with bootstrap-table shortcode](https://i.imgur.com/zWvEpdS.png)

**Comment by pacollins** [comment]
I don't have the time at the moment (as noted by my delayed response) to look for the issue. I'd venture to guess that somewhere in the table CSS I have inadvertently centered everything.

**Comment by pacollins** [comment]
I lied in my last comment - the challenge interested me. The issue is that `td align="x"` is [no longer supported in HTML5](https://www.w3schools.com/tags/att_td_align.asp). The solution is add `table[align=X]` in the [CSS](https://stackoverflow.com/a/40901886). Will do that now.

**Comment by javydekoning** [comment]
@pacollins thanks for looking at this, this seems to only have fixed it for the table header though :)

**Comment by pacollins** [comment]
This  had fixed all of mine (unless it was too late for me to notice). Did
you clear your cache?

**Comment by javydekoning** [comment]
Cloned a fresh copy and used the example site. Left alignment is not working:

```
| Tables        |      Are      |  Cool |
| :------------ | :-----------: | ----: |
| col 3 is      | right-aligned | $1600 |
| col 2 is      |   centered    |   $12 |
| zebra stripes |   are neat    |    $1 |
```

![Imgur](https://imgur.com/qKxJhh8.png)

**Comment by pacollins** [comment]
@javydekoning can you confirm that this is what you are looking for?

![errors](https://user-images.githubusercontent.com/11359433/75097998-41b7e600-557f-11ea-9517-df1ba30a93fd.png)

1. (Yellow) Should be aligned left.
2. (Green) Should match MD alignment - would align left in this example.
3. (Red) Should match MD alignment - would align center in this example.
4. (Blue) should match MD alignment - would align center in this example.

1. My thoughts are that the default table should align center. I feel as though this is a common use that is the most aesthetically pleasing for most tables. Users interested in controlling the alignment can use MD features (`|:------------- |:-------------:| -----:|`) to control alignment. *The addition to the theme would be add `&data-headers[left]`.*
2. I would argue under this style table that forced center align makes more sense. *The addition to the theme would be to remove `float: left` from `::before` and add `text-align: center` to the mobile headers.*
3. The column headers need additional spacing from the row headers. *The addition to the theme would be to add space **or** right align the row headers.*
4. I would argue a stance similar to point 1.

Thoughts?

**Comment by javydekoning** [comment]
`1.` is what I'm looking for. 

While center alignment usually works, it doesn't work well for financial data. Financial data is usually right-aligned while the left most column is left aligned e.g:

```
| Item  | Amount | Price |
| :---- | -----: | ----: |
| Beer  |    16x | $1600 |
| Pizza |     1x |   $12 |
| Cola  |     2x |    $4 |
```
![Imgur](https://imgur.com/IDoJpzf.png)

Regarding the view for 2, 3 & 4:

There should just be spacing between the column (2. Green) & row (3. red) header. Column headers (4.) should always left align, regardless of MD alignment.

![img](https://i.imgur.com/q7426kU.png)

**Comment by pacollins** [comment]
So I think the solution is to not allow customization of the mobile version. You would force left align for 2, 3, and 4; force right align for 5. Since the table pivots, if you match MD, 5-row 1 could be left aligned while 5-row 2 could be right aligned.

I am going to keep playing with it (and maybe restructure the whole table CSS) to see if I can design it better for this MD correction.
