### ISSUE TITLE
BUG: Words are broken incorrectly in post title's.

### ISSUE THREAD

**Issue by javydekoning** [pacollins/hugo-future-imperfect-slim#107]
# Bug Report
## Describe the bug

Words are broken incorrectly in post title's. The theme css uses `break-all` this means words may be broken at any character. Which can result in 

```
This is a long p
ost title
```

## Fix

Change/remove this line: 
https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/assets/scss/main.scss#L1018 

```css
word-break: break-word;
```

Documentation: 
https://www.w3schools.com/cssref/css3_pr_word-break.asp 

as a workaround before this get's fixed you can load a custom CSS like this: 

`yoursite/static/css/custom.css`

```css
.post header {
  word-break: break-word;
}
```

And load it in config.toml 

```toml
  cssFiles              = ["default","/css/custom.css"]
```

**Comment by pacollins** [comment]
See comments in #99 / #94

**Comment by javydekoning** [comment]
That PR seems pretty stale, would you like me to file a new one?

**Comment by pacollins** [comment]
Ideally you should push to that PR so that appropriate credit would be given where necessary (if you referenced my solution), but if you want to rework your own PR, feel free.
