### ISSUE TITLE
BUG: Featured Image Scaling

### ISSUE THREAD

**Issue by aavdberg** [pacollins/hugo-future-imperfect-slim#109]
# Feature Request

## Is your feature request related to a problem?
The blog picture is very big in the header of the blog item

## Solution
Option to specify the size of the picture in the blog items of the header.

**Comment by pacollins** [comment]
I would need to see an example of what you mean.

Reducing the size would require some CSS work to not make the theme look gaudy.

**Comment by aavdberg** [comment]
look at my site www.thecloudadmin.eu.
![image](https://user-images.githubusercontent.com/22030609/75179835-3b6e6900-573b-11ea-94cc-e0c1bae2fe38.png)

**Comment by pacollins** [comment]
Not that I am outright opposed to adjusting it, but you are using an "image" as a "banner." The item that you have attached would be better served as an image within your blog post. Functionally, it serves no real purpose as the "featured image." See [Google's Blog](https://www.blog.google/) where all featured images are wide format.

**Comment by aavdberg** [comment]
Looked at it, and understand your point of view. I would to keep the image in the mini post and can live without image in blog post, or by adding it manually.

**Comment by pacollins** [comment]
To your credit, I am leave this issue because I do think we can adjust the CSS to better serve vertical images.

**Comment by pacollins** [comment]
![image](https://user-images.githubusercontent.com/11359433/85241774-f61d2800-b40a-11ea-9c84-288a5b924981.png)

Tentative design

**Comment by twatzl** [comment]
After discussing this in the PR I did some mockups how this could be solved differently or how the proposed solution could be augmented.

On Widescreens and when the image has a more or less "normal" aspect ratio the layout could look like this
![image](https://user-images.githubusercontent.com/18753370/86542528-aa907100-bf16-11ea-92e2-0f004ee7b199.png)

When using wide images (e.g. panoramas) it could possibly use up the whole horizontal space like this:

![image](https://user-images.githubusercontent.com/18753370/86542555-e9262b80-bf16-11ea-9298-fe2be0503200.png)

And on mobile it could look like this
![image](https://user-images.githubusercontent.com/18753370/86542584-14a91600-bf17-11ea-9d6c-a33fcebe7617.png)

Note the visual elements are not final it's just supposed to visualize the idea of the layout of the elements.
