### ISSUE TITLE
BUG: all titles have the same size

### ISSUE THREAD

**Issue by Jubijub** [pacollins/hugo-future-imperfect-slim#11]
# Bug Report
## Describe the bug
All titles have the same size (

## To Reproduce
1. publish a blog post
2. realise all titles have the same size.

Upon inspection, it seems that this rule is the culprit (line 950 of main.css): 
```
.post>div h1, .post>div h2, .post>div h3, .post>div h4, .post>div h5, .post>div h6, .post>p h1, .post>p h2, .post>p h3, .post>p h4, .post>p h5, .post>p h6 {
    font-size: 1em;
}
```

## Expected behavior
I would expect titles to look different to convey hierarchy. 
Removing this rule works, as all titles are already formatted in a different way
![with the rule](https://user-images.githubusercontent.com/1254368/58428502-9f73dc00-809a-11e9-8457-ed2587d29db2.png)

Here is the same post by unticking the rule in the Dev tools : 
![without the rule](https://user-images.githubusercontent.com/1254368/58428515-a7338080-809a-11e9-8d29-dd1a23c85f36.png)

## Environment
 - **Hugo Version:** 0.55.6
 - **Browser and Version:** Version 75.0.3770.51 (Official Build) beta (64-bit)
 - **Platform:** Desktop
 - **Theme version**
```
commit d36f8892421fe4bf831e8d1cfb8b1dd40b04fae9 (HEAD -> master, origin/master, origin/HEAD)
Author: Patrick Collins <thepatrickcollins@gmail.com>
Date:   Mon May 20 08:29:06 2019 -0400

    Bug fix (#9)
    
    Closes #9
```

**Comment by pacollins** [comment]
I don't have this issue, so I will need further information. 

Can you check the example content at /blob/master/exampleSite/content/blog/examples.md?

**Comment by pacollins** [comment]
Correction: I do have it, must have been an issue with cache.

**Comment by Jubijub** [comment]
Wow, that's a fast fix, thanks for this!

Migrating from future-imperfect, I'm cleaning up things, and finding where the differences are.
I would have done a pull request, but I don't know how you generate the main.min.css

**Comment by Jubijub** [comment]
Hum, I have just updated my repo, and the issue is still present.

Looking at this [commit](https://github.com/pacollins/hugo-future-imperfect-slim/pull/12/commits/bf574e2916c8446c583eef3dd5b20241e950b8ab) I don't see how it is supposed to change the font size.
Did you push the right change ?

**Comment by pacollins** [comment]
I try to do these fixes fast since I know I missed stuff when migrating. Unfortunately a little too fast and I really sure commit to a review system. I have updated it (you might need to do a hard pull). 

To compile the css I have auto-compile-scss package on Atom for when I save the scss. Any compiler would work though (even a web based one). I went back and forth over the accessibility of pure css vs the functionality of scss and decided that, for now, scss made the most sense.

**Comment by Jubijub** [comment]
Does auto-compile-scss produce the minified version of the CSS ? (I am fully supportive of scss by the way)

My question is how do you get the main.**min**.css . To contribute I want to make sure I use the same one, so differences in minification won't be seen as changes when committing.
