### ISSUE TITLE
BUG: Documentation missing on fancybox shortcode

### ISSUE THREAD

**Issue by twatzl** [pacollins/hugo-future-imperfect-slim#110]
Hi, 
I am using this theme since about 4 months, but I just found out that there is a shortcode for fancybox. I found this out only by looking at the original repo https://github.com/pacollins/hugo-future-imperfect
and by looking in the code.

I think it might be useful to either use the same documentation in readme.md or to get rid of the shortcode if it no longer works.

Also the paragraph about the original theme could be clearer. When considering the following sentence: 
```
This version takes that port and modernizes it with CSS Grid and Modern Hugo functions. In addition to the features that were present in the original theme, there are some additional features for you to utlize however you see fit.
```
The question which is still remaining after this paragraph is what features are you talking about. Is it just the CSS grid and modern hugo functions or are there more differences than that.

**Comment by pacollins** [comment]
See #84 about documentation. There are additional features that have yet to be reported to the slimmed theme.

FancyBox is a feature, just not in the documentation. It is documented within the short code file. See below: 
https://github.com/pacollins/hugo-future-imperfect-slim/blob/ab18a49246a1562cbeb8af7ce637bbf8fcc2fac9/layouts/shortcodes/fancybox.html#L1-L18
