### ISSUE TITLE
BUG: Buttons not expanded, as shown in the preview

### ISSUE THREAD

**Issue by ChrisK91** [pacollins/hugo-future-imperfect-slim#111]
# Bug Report
## Describe the bug

The preview shows the "read more" button expanded across the whole width

## To Reproduce

1. Create a post with long text
2. Notice the "Read more..." button on the homepage

## Expected behavior

1. The "Read more..." button should expand and be aligned properly

## Environment

 - **Hugo Version:** v0.64.1/extended
 - **Browser and Version:** Edge Version 81.0.416.6 (Official build) dev (64-bit)
 - **Platform:** Desktop
 - **Link to Project:** https://christian-j.com

**Comment by pacollins** [comment]
The intended behavior is actually no longer a large button across the bottom. It doesn't make sense outside of mobile application. Now, the current placement on your site doesn't make sense either, it should probably be on the right-hand side.
