### ISSUE TITLE
BUG: Missing Translation : Mail Subject

### ISSUE THREAD

**Issue by giom-mallet** [pacollins/hugo-future-imperfect-slim#124]
# Bug Report
## Describe the bug
In the Social Network Sharing Buttons (layouts/partials/share_buttons.html
The email subject is in hardcoded in English in the Mail sharing button : 

`{{ else if eq . "email" }}
        <a href="mailto:?subject=Check out this post by {{ $author }}&amp;body={{ $permalink }}" target="_blank" class="share-btn email" data-proofer-ignore>
          <i class="fas fa-envelope"></i><p>&nbsp;Email</p>
        </a>`

## To Reproduce
Switch to any language different from English
Try to share an article

## Expected behavior
Ideally a translation should be available for any language

**Comment by pacollins** [comment]
Good catch!
