### ISSUE TITLE
Theme Demo broken on Hugo themes website

### ISSUE THREAD

**Issue by onedrawingperday** [pacollins/hugo-future-imperfect-slim#129]
Hello @pacollins 

There is a syntax error in [line 28](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/partials/share-buttons.html#L28) of `layouts/partials/share-buttons.html`

i.e. `{[ i18n "Check_Out"]}`

Once you push a fix, feel free to close this issue.

**Comment by pacollins** [comment]
Thanks for the catch @onedrawingperday. Odd that I didn't get the error in testing or maybe it snuck by. Anyway, it has been fixed.
