### ISSUE TITLE
How can I dd more items on menu

### ISSUE THREAD

**Issue by rubensdemelo** [pacollins/hugo-future-imperfect-slim#13]
I would like to add more options on menu. Create a menu item on conifg.toml, create a folder in contet and the new menu should be ready.

```
  [[menu.main]]
    name              = "Categories"
    url               = "/categories/"
    identifier        = "fas fa-sitemap"
    weight            = 4

  [[menu.main]]
    name              = "Articles"
    url               = "/articles/"
    identifier        = "far fa-envelope"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    url               = "/contact/"
    identifier        = "far fa-envelope"
    weight            = 6
```

<img width="238" alt="Captura de tela 2019-06-05 05 20 28" src="https://user-images.githubusercontent.com/1351177/58941303-d9577900-8751-11e9-95a5-a0c06b4a7884.png">

And this new item doesnt appear on menu bar:

<img width="304" alt="Captura de tela 2019-06-05 05 24 02" src="https://user-images.githubusercontent.com/1351177/58941456-33583e80-8752-11e9-84eb-594fdca434ae.png">

**Comment by pacollins** [comment]
1. Please follow the issue templates, this would be a bug - not a feature request - so that I can accurately address your problem.
2. I cannot recreate this. I am able to create as many menu items as I would like. If you would like, please create a **bug** report and fill out all applicable information.

**Comment by rubensdemelo** [comment]
I gotcha. When create a new menu, I have to change de icon. Now it works fine. Thank you.
