### ISSUE TITLE
FEATURE: Table Of Contents

### ISSUE THREAD

**Issue by Ronald-TR** [pacollins/hugo-future-imperfect-slim#132]
# Feature Request

## Is your feature request related to a problem?
No.
I'm writing a blog with this theme, but i miss the table of contents feature. Preferable the sidebar, something like `ananke` theme (and the official hugo docs) does.

## Solution
 I added a shortcode that renders a toc (when the parameter `toc = true` into my .md files) into `layouts/_default/content-single.html`:

```html
....
{{ if .Params.toc }}
  <h6>
    {{ .TableOfContents }}
  </h6>
  {{ end }}
  <div class="content">
    {{ .Content }}
  </div>
....
```
It renders the index properly on the post. But i miss the sidebar, which in my opinion is very useful for navigate trough the post sections without going to the summary every time.

Also, congrats for the good work!

**Comment by pacollins** [comment]
The easiest solution would probably be to utilize Javascript to build the TOC based on the content present.

**Comment by pacollins** [comment]
Upon further evaluation, it seems I miss understood.

You have the TOC generator, but you are looking for a presentation sidebar. Is this something that you would only see on larger screens? If so, we could easily throw it as a floating object in the page margin.

**Comment by pacollins** [comment]
https://gohugo.io/content-management/toc/

Can be implemented, but would need styling.
