### ISSUE TITLE
FEATURE: Gallery Page

### ISSUE THREAD

**Issue by ohelabs** [pacollins/hugo-future-imperfect-slim#133]
I have struggled to find a hugo theme that supports blogs and photography galleries... this theme has a lot of potential.

I have managed to cobble together a gallery page from the about page and using shortcode from [hugo-easy-gallery ](https://github.com/liwenyip/hugo-easy-gallery) I was able to update some of the code to use modern binarys and update the photoswipe.js. Another issue I had implementing this was the CSS which I was able to fix.

**Comment by pacollins** [comment]
So the theme supports [fancybox](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/shortcodes/fancybox.html) at the moment as an [image gallery](http://fancyapps.com/fancybox/3/).

Is there something that is missing from this that you need? Or is the fact that we still haven't gotten around to documenting everything? Haha

**Comment by pacollins** [comment]
Closing due to a feature currently supporting this with no additional comments.
