### ISSUE TITLE
hugo start result

### ISSUE THREAD

**Issue by vlpoliakov** [pacollins/hugo-future-imperfect-slim#137]
$hugo server 
Building sites … ERROR 2020/05/02 01:39:34 render of "home" failed: execute of template failed: template: _default/index.html:3:5: executing "_default/index.html" at <partial "head" .>: error calling partial: "/home/vnp/HUGO/s1/themes/hugo-future-imperfect-slim/layouts/partials/head.html:37:41": execute of template failed: template: partials/head.html:37:41: executing "partials/head.html" at <resources.Concat>: error calling Concat: resources in Concat must be of the same Media Type, got "text/x-scss" and "text/css"
ERROR 2020/05/02 01:39:34 render of "taxonomyTerm" failed: execute of template failed: template: taxonomy/category.terms.html:3:5: executing "taxonomy/category.terms.html" at <partial "head" .>: error calling partial: "/home/vnp/HUGO/s1/themes/hugo-future-imperfect-slim/layouts/partials/head.html:37:41": execute of template failed: template: partials/head.html:37:41: executing "partials/head.html" at <resources.Concat>: error calling Concat: resources in Concat must be of the same Media Type, got "text/x-scss" and "text/css"
ERROR 2020/05/02 01:39:34 failed to render pages: render of "taxonomyTerm" failed: execute of template failed: template: taxonomy/tag.terms.html:3:5: executing "taxonomy/tag.terms.html" at <partial "head" .>: error calling partial: "/home/vnp/HUGO/s1/themes/hugo-future-imperfect-slim/layouts/partials/head.html:37:41": execute of template failed: template: partials/head.html:37:41: executing "partials/head.html" at <resources.Concat>: error calling Concat: resources in Concat must be of the same Media Type, got "text/x-scss" and "text/css"
Built in 14 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_f300667da4f5b5f84e1a9e0702b2fdde" not found in file cache

**Comment by pacollins** [comment]
I cannot reproduce this error. Can you make sure you have `hugo_extended_0.69.2` and the latest, unedited, version of the theme?

If the error still occurs, please post a link to your project.

**Comment by vlpoliakov** [comment]
I DO NOT use hugo extended!
Now it's ok!
Thank you very much and excuse me!

**Comment by vlpoliakov** [comment]
I DO NOT USE extended!! Big thanx
