### ISSUE TITLE
FEATURE: add "Strava" social network icon and quick link

### ISSUE THREAD

**Issue by tmswfrk** [pacollins/hugo-future-imperfect-slim#139]
# Feature Request

## Is your feature request related to a problem?
Not a problem at all, but given how many other social networks are included here, I'd love to have the option to add Strava (specifically a social platform for cycling, running, and other sports) as a configurable option.

## Solution
Should be just mimicking existing references for LinkedIn, Instagram, or Vimeo to add a new one that builds a link to a particular user's Strava athlete page. As an example, I could provide user "123456" to the Strava key in the config.toml file and then have it build a link to the athlete page at https://www.strava.com/athletes/123456. 

## Alternatives
No alternative really. Just a feature request.

## Additional Context
Just mimic the same functionality as elsewhere.

**Comment by pacollins** [comment]
Should be simple enough since [FontAwesome has the Strava logo](https://fontawesome.com/icons/strava?style=brands).

**Comment by pacollins** [comment]
@tmswfrk - I would like your feedback on a proposed adjustment I made in the PR. It would be potentially theme-breaking, but I think it would help in the long run, and allow users to organize the icons how they want to.

**Comment by pra-dan** [comment]
Hey @pacollins I plan to add a similar icon. How should I proceed ? 

I think I also need some getting started guide to make some minor changes to the theme...

**Comment by pacollins** [comment]
@pra-dan, is it through FontAwesome?

**Comment by pra-dan** [comment]
No, I downloaded it from another site as a png
