### ISSUE TITLE
BUG: hugo version 0.7

### ISSUE THREAD

**Issue by arguskao** [pacollins/hugo-future-imperfect-slim#141]
# Bug Report
## Describe the bug

I add a post , and want to produce new article.

When I write hugo.

It appears

Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: post/single.html:3:5: executing "post/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: _internal/schema.html:22:82: executing "_internal/schema.html" at <.Params.tags>: range can't iterate over

## Environment

 - **Hugo Version:** [e.g. 0.46]
 - **Browser and Version:** [e.g. Chrome 74.0.3729.108]
 - **Platform:** [e.g. Desktop/Mobile]
 - **Link to Project:**

**Comment by pacollins** [comment]
1. Ensure you are using Hugo extended edition
2. If you are using that, please post a link to your project. I just got the most recent version and did not have this error.

**Comment by arguskao** [comment]
Thanks for your kindness reply.
I do not know what is Hugo extended edition.

I use mac, I use brew install hugo.

And I use the theme several months ago.

**Comment by pacollins** [comment]
https://github.com/gohugoio/hugo/releases/tag/v0.71.0

It is at the bottom there. We shifted to this version when we made #66.

**Comment by arguskao** [comment]
I have reintall hugo for extend version 0.71.
https://github.com/gohugoio/hugo/releases/download/v0.71.0/hugo_extended_0.71.0_Linux-64bit.deb

https://github.com/arguskao/asean

**Comment by arguskao** [comment]
I find the error.
If my article is YAML that is good.
TOML is bad.

**Comment by kprohith** [comment]
Ive getting the same error while using Netflify CMS and passing tags in the fields using

- { label: 'Tags', name: 'tags', widget: 'string'}

**Comment by pacollins** [comment]
@kprohith - Can you provide a little more information? I do not use Netlify CMS, so it is foreign to me.
