### ISSUE TITLE
BUG: Pop Out Menus Not Working as Expected on Mobile

### ISSUE THREAD

**Issue by tmswfrk** [pacollins/hugo-future-imperfect-slim#144]
# Bug Report
## Describe the bug
It seems that when the site is viewed on a mobile device that the pop out menus at the top do not function as they should. The root item simply just gets clicked instead of using the flyout feature that I remember it being.

I'm not sure if I simply hadn't noticed this before, or perhaps I have changed something recently locally that only showcases this issue.

## To Reproduce
Chrome dev tools -> set to mobile -> load up page -> try to open pop out menu (either left site map or right language selector)

## Expected behavior
I thought this used to work for me on mobile, but perhaps I'm wrong. The pop out / fly out should happen to allow for other menu items to appear and be selectable in a new slider box.

## Environment
Just using Apple for all this, but no reason why it wouldn't appear on any mobile device.

 - **Hugo Version:** [v0.57.2/extended darwin/amd64]
 - **Browser and Version:** [Chrome 81.0.4044.138]
 - **Platform:** [Mobile]
 - **Link to Project:** www.bicyclewatercooler.com

## Additional context
I don't see any other errors in my console log when the page loads except for a favicon.ico missing (which I haven't looked into yet, but can't imagine it would be related somehow).

**Comment by pacollins** [comment]
I'm out today, but it seems to be working on the themes demo (
https://themes.gohugo.io/theme/hugo-future-imperfect-slim/).

I'll investigate more tomorrow.

**Comment by tmswfrk** [comment]
Hey, thanks for the link. I ended up sorting it out. I had somehow decided to exclude the add_on.js reference by commenting it out in my config.toml. D'oh! No need to look into it further.
