### ISSUE TITLE
BUG: Links on category page use http instead of https when page is served via https.

### ISSUE THREAD

**Issue by twatzl** [pacollins/hugo-future-imperfect-slim#145]
Hi, so I just noticed an issue with http/https and I am not sure where it exactly comes from.

When in the categories page of my blog the links will redirect to http instead of https. 

![image](https://user-images.githubusercontent.com/18753370/83395743-1dc83400-a3fb-11ea-9bf1-0592368d23b9.png)

The strange thing is that these paths are indeed relative paths and not absolute ones. So I am a bit surprised the redirect does not work.

To be fair I have not yet checked the configuration of my blog because right now I am busy debugging the reverse proxy, but I can't imagine what could be misconfigured that this happens.

However I think it should be investigated as it is a potential security issue.

You can try it out for yourself here: https://twatzl.eu/categories/
Note that I am still working on the configuration of the reverse proxy, so there might still be issues from that.

**Comment by pacollins** [comment]
So I went to your site main page and clicked on categories and it seems to be redirecting me to `https://twatzl.eu/categories/`. Even if I go to `http://twatzl.eu/categories/` it is forcing it to the `https` version. Maybe the forwarding was still updating when you were testing?

**Comment by pacollins** [comment]
I have checked again today, and the issue doesn't seem to be persisting. I will close the issue, but feel free to comment again if it persists.

**Comment by twatzl** [comment]
I see. Yes, my reverse proxy is configured to automatically redirect to https if you browse via http. But http shouldn't be requested in the first place.

If you look in the debug tools you can see that there is a request via http sent which is then redirected to https by the reverse proxy.

That http request should not be sent as it is a possible way for a man in the middle to redirect blog viewers elsewhere.

![image](https://user-images.githubusercontent.com/18753370/83562317-a3da9c80-a519-11ea-9f50-ce3bb26d55af.png)

**Comment by pacollins** [comment]
I will investigate further, but this is a little beyond me. You might cross-post to the Hugo forums.

**Comment by pacollins** [comment]
So it seems like whenever it goes to a page *without* a trailing slash it goes through `http`, but when there *is* a trailing slash, it goes through `https`.

This is a relatively easy fix to make on the theme, but my question is whether this is technically a Hugo security bug.

**Comment by twatzl** [comment]
Sorry again for the late reply. I agree with you. I didn't have time yet to investigate either (and unfortunately won't have for the forseeable future). It might also be connected with the use of Traefik as a reverse proxy here. Because even when I enter the address (with https, but without trailing slash) in the browser I can see the same redirection behavior. 

Thanks for taking a look.
