### ISSUE TITLE
How to replace font for code snippets ?

### ISSUE THREAD

**Issue by pra-dan** [pacollins/hugo-future-imperfect-slim#148]
Hello. I am using this theme for my static site and completely love it. :smiley: 
But I would like to change the font used to show the `code snippets` and the 
```
code blocks
```
Currently, they are : 
![Screenshot from 2020-06-12 11-26-43](https://user-images.githubusercontent.com/46529961/84469864-aa96ab80-ac9f-11ea-80ef-456138178777.png)

and I find the font it too fine/thin for me. 

How can I change it? 
P.S. I am new to HTML+CSS and can't find a way.

**Comment by pacollins** [comment]
Thanks for the kind words!

There are actually a couple of ways.

1. You can add `code {/*YourStyleHere*/}` to [`static/css/add-on.css`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/exampleSite/static/css/add-on.css) and modify as you desire.
2. We actually use use [highlight.js](https://highlightjs.org/static/demo/), so you could select a style from their site and replace `highlightjsTheme = "github"` in the `config.toml`.

I'm going to go ahead and close this issue, but feel free to keep commenting if you need assistance.

**Comment by pra-dan** [comment]
Thank you very much. 

I request you to clarify some other doubts in this thread as it would be messy to open new issue for each one. 

1. I can't see the date updated on my blogs like here
![Screenshot from 2020-06-12 23-07-25](https://user-images.githubusercontent.com/46529961/84531490-52dd5c00-ad02-11ea-994a-bfc1e7a6b29d.png)

2. Images won't load. I am using GitHub flavour of markdown but it won't work. I use `![img_name](img_link)`

3. How can I add a widget (like adding a button next to the Search button, that redirects to my github profile) ?

I know this may be too many questions but please try to understand that I have literally no experience in this :monkey:

**Comment by pacollins** [comment]
1. I assume by marking it out, you have it fixed?
2. Can you provide an example of your link? It should be similar to `![Cat](img/animals/cat.jpg)`
3. You would need to change the template. Check out the [readme#non-development](https://github.com/pacollins/hugo-future-imperfect-slim#non-development). The file you would be recreating/adjusting would be `layouts/partials/site-header.html`

No problem on the questions, I'm here to help. 😄

**Comment by pra-dan** [comment]
Thank You so much for the constant help.
1. Yeah I had solved that one.
2. My images are stored in `static/img/yolov3_decoding/man1.png` and I use the statement `![img_1](static/img/yolov3_decoding/man1.png)` in the markdown file.  I get 
3. I will look into it later, not so important right now, but still very helpful.

**Comment by pacollins** [comment]
So `static` is just a directory of files that Hugo doesn't have to process. When you run `hugo` on your site, it compiles everything into the `public` directory. At this point everything in `static` is extracted and placed into `public`. As such, you don't need to include `static` in your link. You want `[img_1](img/yolov3_decoding/man1.png)`.

**Comment by pra-dan** [comment]
Also, regarding the overall font of the blogs, how can I change it and what options do I have. I can't find any related field in the `.toml` file. 

I am also unable to add disqus to the comment section.

**Comment by pra-dan** [comment]
> So `static` is just a directory of files that Hugo doesn't have to process. When you run `hugo` on your site, it compiles everything into the `public` directory. At this point everything in `static` is extracted and placed into `public`. As such, you don't need to include `static` in your link. You want `[img_1](img/yolov3_decoding/man1.png)`.

Hey Patrick, I tried this and it still does not work :(

**Comment by pacollins** [comment]
My apologies, I forgot the exclamation mark. `![img_1](img/yolov3_decoding/man1.png)`.

To change the font you would need to change the CSS. Keep in mind that a theme is not intended to be fully customization. The `config.toml` is more intended to modify *content* of the theme than the overall *style* of the theme. Changing the style of a theme defeats the point of using a theme, which has been meticulously crafted to look good.

That being said, I *highly* recommend you spend more time exploring the Hugo documentation.

As for Disqus, you should only have to add your shortname to the `config.toml` at `disqusShortname         = ""`. That being said, I don't have enough information to diagnose that issue.

**Comment by pra-dan** [comment]
Hey @pacollins the command `![img](img/yolov3_decoding/man1.png)` still does not work... I think there's a bug

**Comment by pra-dan** [comment]
Ok I found the solution. It was meant to be `![img](/img/yolov3_decoding/man1.png)` 

So, the `/` is what changed it :)
