### ISSUE TITLE
BUG: Demo Site Search Links Broken

### ISSUE THREAD

**Issue by twatzl** [pacollins/hugo-future-imperfect-slim#150]
# Bug Report

## Describe the bug

when using the search on https://themes.gohugo.io/theme/hugo-future-imperfect-slim/#search-input the search does not work/redirect to the wrong url

## To Reproduce

1. Go to https://themes.gohugo.io/theme/hugo-future-imperfect-slim/#search-input
2. enter something in the search
3. click on a result

**Comment by pacollins** [comment]
https://github.com/pacollins/hugo-future-imperfect-slim/blob/0a02e0bf8c446376d9b9cc89060248f90398f70c/layouts/_default/index.json.json#L8

`index.json` loads permalinks. This error only occurs on the theme site (as far as I know) and matches a couple of other issues I've had with the demo.

**Comment by pacollins** [comment]
@VincentTam - This might be an extension of #232 and #230.

**Comment by pacollins** [comment]
Issue resolved since the theme site no longer hosts demos.
