### ISSUE TITLE
BUG: Hugo 0.60 removed inline HTML for Markdown Files

### ISSUE THREAD

**Issue by pra-dan** [pacollins/hugo-future-imperfect-slim#151]
I am having problem centering and resizing images in my site. Conventionally, I used Markdown, but as it does not provide these features, I am falling back to CSS, of which I have no knowledge. I still googled it and tried things like 
```
# Attempt 1
<span style="display:block;text-align:centre">![anchor](/img/yolov3_decoding/anchor.png)</span>
 
# Attempt 2
<a href="/img/yolov3_decoding/anchor.png" class="image featured">
  <img src="/img/yolov3_decoding/anchor.png" alt="Pic 1">
</a>

# Attempt 3
<img src="/img/yolov3_decoding/anchor.png?style=centerme" alt="Image" width="800" height="600" style="display: block; margin: 0 auto" />
```

But they don't seem to work.

**Comment by pacollins** [comment]
1. Utilize the built-in Hugo shortcode, [`figure`](https://gohugo.io/content-management/shortcodes/#figure)
    `{{< figure src="path" >}}`
2. Utilize the theme's built-in shortcode [`fancybox`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/shortcodes/fancybox.html). This is currently functional, but I am probably going to recreate it and make it more generic later, so I can't ensure it's continued functionality.
    `{{< fancybox path="path" file="file" caption="caption" gallery="gallery" >}}`
3. Wrap your image in a container.
```
<div style="text-align:center;">
  <img src="path">
</div>
```

**Comment by pra-dan** [comment]
@pacollins I don't think any of the options help in aligning the image to the center. Also, the captions to the images also align to the left.

**Comment by pacollins** [comment]
So upon further investigation, [Hugo 0.60](https://gohugo.io/news/0.60.0-relnotes/) removed inline HTML for Markdown. To turn this feature back on, you need to add the following to your `config.toml`.

```
[markup.goldmark.renderer]
unsafe= true
```

As such, I am reopening and retitling this so it can be adjusted on the theme level. I'm not quite sure why they would turn this feature off.

**Comment by pra-dan** [comment]
Ok @pacollins this works now. 
Although, I would be thankful if you could direct me to the complete options/arguments possible when wrapping my image in a container... I wish to take control of the image size and the caption

**Comment by RyanTG** [comment]
Thanks for that markup snippet. 

I just exported my wordpress blog for hugo using the [wordpress to hugo exporter](https://github.com/SchumacherFM/wordpress-to-hugo-exporter), and all my img links were still raw html. I thought I was hosed here.
