### ISSUE TITLE
FEATURE: Headless CMS Support

### ISSUE THREAD

**Issue by stephenajulu** [pacollins/hugo-future-imperfect-slim#153]
# Feature Request
Kindly add a CMS
## Is your feature request related to a problem?
Yes, adding posts is not easy using markdown.
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]]
Adding post with markdown is quite difficult, you have to remember that # is for headings and such. 
## Solution
With a CMS e.g Forestry or Netlify CMS it becomes easier allowing people's writing art to just flow without remembering other things
[A clear and concise description of what you want to happen.]

## Alternatives
Contentful or Sanity
[A clear and concise description of any alternative solutions or features you've considered.]

## Additional Context

[Add any other context or screenshots about the feature request here.]

**Comment by pacollins** [comment]
For anyone interested in implementing this - I recommend Netlify CMS built-in integration for consistency (Netlify forms is already supported on the contact form),
