### ISSUE TITLE
BUG: Invalid hyperlinks in term list pages of non-default languages

### ISSUE THREAD

**Issue by xinii** [pacollins/hugo-future-imperfect-slim#156]
# Bug of invalid hyperlinks in term list pages of non-default languages

## The description of the bug

When clicking hyperlinks in the **categories** and **tags** pages of **non-default language**,
the URL in the address bar of the browser will become
`http://localhost:1313/{language-code}/{language-code}/tags/{the-tag-clicked}/`
and the page can not be opened correctly.
The categories page has the same issue that all the hyperlinks on the page are invalid.

## Bug reproduction

1. Clone the latest repo to local.
```
git clone https://github.com/pacollins/hugo-future-imperfect-slim.git
```

2. Copy the subfolder `exampleSite` inside to someplace.
```
cp -r hugo-future-imperfect-slim/exampleSite example-site-for-test
mkdir example-site-for-test/themes
mv hugo-future-imperfect-slim example-site-for-test/themes/hugo-future-imperfect-slim
cd example-site-for-test
hugo server -t hugo-future-imperfect-slim --watch
```

3. Open a browser and input `http://localhost:1313/fr/tags/` to the address bar of the browser.

4. Click `css`, `emoji` or  `html`, etc. in this tags list page

Then the URL in the address bar of the browser becomes `http://localhost:1313/fr/fr/tags/css/`
and displays `404 page not found`.
(I tried the latest version of Firefox and Chrome under macOS and Windows 10)

## Environment

```
$ hugo env

Hugo Static Site Generator v0.67.0/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.14"
```

## Solution in my case

- Open the following file through any editor.
```
layouts/_default/terms.html
```
- Locate the following line.
```
<a href="{{ .Page.Permalink | relLangURL }}">{{ .Page.Title }}<span style="float:right;">{{ .Count }}</span></a>
```
- Modify to the following content.
```
<a href="{{ .Page.Permalink }}">{{ .Page.Title }}<span style="float:right;">{{ .Count }}</span></a>
```

**Comment by pra-dan** [comment]
This is also the case with re-clicking the article thumbnail (on the left column) once the article is already opened. Suppose, I go to my site and see that I have my article listed in the left column as
![Screenshot from 2020-07-04 13-38-17](https://user-images.githubusercontent.com/46529961/86508216-d5d26d80-bdfb-11ea-8dfa-5ef0bea80905.png)

Now, if I click it, It opens up but without my logo visible (just like it would fail to load...) but the article is visible. 
![Screenshot from 2020-07-04 13-38-36](https://user-images.githubusercontent.com/46529961/86508259-3497e700-bdfc-11ea-8b75-d3ce320fe891.png)


Now, if I again click on the thumbnail of the same article, I get, 
![Screenshot from 2020-07-04 13-38-53](https://user-images.githubusercontent.com/46529961/86508243-13cf9180-bdfc-11ea-9be0-1f8139b5b389.png)

_Also, look at the address in this screeshot_

**Comment by pacollins** [comment]
When I reached out to you, it seemed that the issue was templating on the terms page was not language-specific.

**Comment by xinii** [comment]
@pra-dan - In my environment, I have no problem which you reported, but when I saw the URL on the screenshot, I guess that would be an individual issue about the configuration? For example, the `baseurl` variable in `config.toml` file is set to a relative path. e.g. `http://` or `https://` is omitted in front of the domain.

@pacollins - I have tested the latest repo, unfortunately, it seems that this problem has not been fixed in my environment.
The performance of the `master` branch is the same as before, that is, a situation like `/fr/fr` will appear when I click the link in the list on the term pages. When I checkout the `reduce-specificity` branch and try `hugo server`, the following error report will appear.

```
Building sites … ERROR 2020/07/08 01:19:41 render of "page"
failed: execute of template
failed: template: _default/single.html:8:9: executing "main" at <.Render>: error calling Render: "/path/example-site-for-test/content/blog/markdown-syntax.md:13:17": failed to execute template ["featured"] v: "/path/example-site-for-test/themes/hugo-future-imperfect-slim/layouts/_default/featured.html:13:17": execute of template
failed: template: _default/featured.html:13:17: executing "_default/featured.html" at <.src>: can't evaluate field src in type string
ERROR 2020/07/08 01:19:41 render of "page"
failed: execute of template
failed: template: _default/about.html:11:9: executing "_default/about.html" at <partial "site-sidebar" .>: error calling partial: execute of template
failed: template: partials/site-sidebar.html:9:13: executing "partials/site-sidebar.html" at <.Render>: error calling Render: "/path/example-site-for-test/content/blog/markdown-syntax.md:13:17": failed to execute template ["featured"] v: "/path/example-site-for-test/themes/hugo-future-imperfect-slim/layouts/_default/featured.html:13:17": execute of template
failed: template: _default/featured.html:13:17: executing "_default/featured.html" at <.src>: can't evaluate field src in type string
ERROR 2020/07/08 01:19:41 render of "page"
failed: execute of template
failed: template: _default/contact.html:11:9: executing "_default/contact.html" at <partial "site-sidebar" .>: error calling partial: execute of template
failed: template: partials/site-sidebar.html:9:13: executing "partials/site-sidebar.html" at <.Render>: error calling Render: "/path/example-site-for-test/content/blog/markdown-syntax.md:13:17": failed to execute template ["featured"] v: "/path/example-site-for-test/themes/hugo-future-imperfect-slim/layouts/_default/featured.html:13:17": execute of template
failed: template: _default/featured.html:13:17: executing "_default/featured.html" at <.src>: can't evaluate field src in type string
ERROR 2020/07/08 01:19:41 render of "page"
failed: execute of template
failed: template: _default/single.html:8:9: executing "main" at <.Render>: error calling Render: "/path/example-site-for-test/content/blog/placeholder-text.md:13:17": failed to execute template ["featured"] v: "/path/example-site-for-test/themes/hugo-future-imperfect-slim/layouts/_default/featured.html:13:17": execute of template
failed: template: _default/featured.html:13:17: executing "_default/featured.html" at <.src>: can't evaluate field src in type string
Built in 102 ms
Error: Error building site: failed to render pages: render of "page"
failed: execute of template
failed: template: _default/single.html:8:9: executing "main" at <.Render>: error calling Render: "/path/example-site-for-test/content/blog/emoji-support.md:13:17": failed to execute template ["featured"] v: "/path/example-site-for-test/themes/hugo-future-imperfect-slim/layouts/_default/featured.html:13:17": execute of template
failed: template: _default/featured.html:13:17: executing "_default/featured.html" at <.src>: can't evaluate field src in type string
```

**Comment by pacollins** [comment]
That error comes from needing to update the front matter of your posts per the guidelines on the PR.

That being said, thanks for confirming that you do not see Pra-dan's issue. I will try to further investigate the issue.

**Comment by xinii** [comment]
Thank you for answering the reason why I got that error in the `reduce-specificity` branch. For the sake of simplicity, I removed all the `images` attribute in the front-mater of all example posts and tested it. However, the same as the `master` branch, this issue still exists. If there is anything else that can help you investigate, please let me know, and thanks again for developing this project.

**Comment by pacollins** [comment]
So after looking further, it seems you are correct.

 If you would like to make the PR so you can get credit @xinii, feel free. If not, I'd be happy go ahead and make the change.

**Comment by pra-dan** [comment]
@xinii @pacollins Thanks for the hint. I got it right.

**Comment by xinii** [comment]
> So after looking further, it seems you are correct.
> 
> If you would like to make the PR so you can get credit @xinii, feel free. If not, I'd be happy go ahead and make the change.

Thank you for investigating this issue, I just created a PR, you could confirm it.

**Comment by xinii** [comment]
I created the PR #158 to solve this problem, so I will close the issue.
