### ISSUE TITLE
BUG: Truncated formatting of categories in the post meta

### ISSUE THREAD

**Issue by kdbruin** [pacollins/hugo-future-imperfect-slim#161]
# Bug Report

## Describe the bug

Although the category name is small and should easily fit in the allocated space, it is displayed truncated. See the attachment.

The category name is "wandelen".

## To Reproduce

My site is not live yet but I've created a blog post with categories

 -  "wandelen"

and tags

 - "trage tocht"
 - "planken wambuis"
 - "natuurmonumenten"

## Expected behavior

I would expect the category name not be truncated.

## Screenshots

<img width="955" alt="Screenshot 2020-07-13 at 12 07 19" src="https://user-images.githubusercontent.com/3851711/87293205-436c5100-c502-11ea-81f3-55d2f2aab754.png">
## Environment

 - **Hugo Version:** [0.73]
 - **Browser and Version:** [Safari 13.1.1]
 - **Platform:** [Desktop]

**Comment by pacollins** [comment]
I believe I fixed this as part of #154 - would you mind checking out that PR?

It is ready to merge, I am just waiting for one or two more reviews.

**Comment by kdbruin** [comment]
I'm no git guru so how do I go about this using the theme as a submodule?

**Comment by pacollins** [comment]
If you are using it as a sub module, you will not be able to check out that PR - which is fine.

If you have a normal fork of the theme you can do the following:

```
git fetch origin pull/154/head:reduce-specificity
git checkout reduce-specificity
cd ../../
hugo server
```

**Comment by kdbruin** [comment]
This does show the categories and tags but my "featured" image is now very small. Need to figure out from the description and the changes what to do here before I migrate more of my old blog posts.

**Comment by pacollins** [comment]
My hope is to merge this July 20th.

Since you are new to the theme, I would venture to guess the only change you need to make is the 5th bullet point!

**Comment by kdbruin** [comment]
I had to make a few changes to the features.html file to allow for images inside of page bundles and found that my current images don't fit the box anymore. Is it possible to add a "fill" or "cover" value for stretch as well and use

    object-fit: cover

for this?

**Comment by pacollins** [comment]
I need more information and/or picture about what change you made and why.

If you want it to stretch both ways, I didn't allow that for this reason:

![image](https://user-images.githubusercontent.com/11359433/87318490-6abd2100-c4f6-11ea-8293-9bd429fa3c6b.png)

**Comment by kdbruin** [comment]
What I did to features.html is not relevant except for the following addition:

        <img {{ with $stretch }}class="{{ if or (eq (lower .) "vertical") (eq (lower .) "v") }}stretchV{{ else if or (eq (lower .) "horizontal") (eq (lower .) "h") }}stretchH{{ else if or (eq (lower .) "cover") (eq (lower .) "c") }}cover{{ end }}" {{ end }}src="{{ $src }}" alt="{{ $alt }}">

I've included an additional stretch value of "cover" or "c" and added the following to add-on.css:

    .image img.cover {
      object-fit: cover;
      width: 100%;
    }

This will use the full width of the box for the image, place the image in the center of the box and because of the "overflow: hidden" on the .image class the excess is removed. This results in a non-distorted image that covers the complete box.

<img width="955" alt="Screenshot 2020-07-13 at 16 55 30" src="https://user-images.githubusercontent.com/3851711/87319294-b806b600-c529-11ea-9e7d-51aaa6a077d4.png">

**Comment by pacollins** [comment]
I see... I think that I could add this as a parameter to `stretch` as `cover` or `fill`. I'll move this discussion to the pr.
