### ISSUE TITLE
BUG: No meta title or description on home page

### ISSUE THREAD

**Issue by RyanTG** [pacollins/hugo-future-imperfect-slim#162]
# Bug Report

## Describe the bug

The meta params in the config file are not populating the title and description on the site's home page.

## To Reproduce

1. Go to https://themes.gohugo.io/theme/hugo-future-imperfect-slim/
2. Inspect or view source, or paste the link into something like Slack that grabs the meta data.
3. See missing content:

````
<meta itemprop="name" content="">
<meta itemprop="description" content="">
````

## Expected behavior

I expect [the params.meta values](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/exampleSite/config.toml#L28) in the config file to populate those fields.

This is not an issue when viewing posts. On posts, the description is populated from the front matter or from the first words of the post.

## Additional context

I could try and dig into this. I'm not a Hugo expert, though. I'm still trying to fully understand the files where the fix seems appropriate. Either
https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/partials/head.html
or
https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/partials/meta.html

**Comment by RyanTG** [comment]
The solution I found is to move:

````
description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
author              = "HTML5UP and Hugo"
````
out of `[params.meta]` and put it directly under `[params]`. 

Source: https://gohugo.io/variables/site/#the-site-params-variable

If you agree with this, I could make a PR.

**Comment by pacollins** [comment]
So it doesn't look like "Author" is even a supported value in the Hugo meta templates for list pages:

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/schema.html

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html

Thoughts?

**Comment by RyanTG** [comment]
Oh yeah, you're right. I believe I kind of lost the narrative at the end there when I included "Author". And I'm not exactly sure why the "name" prop wasn't showing up for me, since that is populated by "title". But now it's fine.

So, my revised solution is to only move description into the top-level params key.

**Comment by pacollins** [comment]
Well, I only said that to say this:

I am by no means an SEO expert. The built-in Hugo templates could be great, or terrible. I am wondering if it worthwhile for us to just make our own schema/meta template. As far as I know, the maintenance of the internal Hugo templates is pretty uneventful.

This issue that you posed made me realize that with the new image configuration, the images will not populate into the default templates opengraph tags.

**Comment by pacollins** [comment]
I know @tmswfrk has been one of the few people to mention SEO. I'm not sure of his knowledge, but I'd love to get his take on the internal Hugo templates on whether they have bloat and/or are missing anything.

**Comment by RyanTG** [comment]
Ah, I recently moved [my site](https://blueskiesabove.us/) from wordpress to hugo, and am still in the process of editing all the front matter - so I hadn't used Image and didn't realize it wasn't fully working with OG. 

That said, I don't yet have an opinion on whether to improve the theme's compatibility with the internal templates, or to make our own. Though I lean toward using the internal templates.

I have a few other hugo sites, using different themes, and I'll take a look at what they're doing for SEO.

**Comment by RyanTG** [comment]
Upon some further looking:

I added `images = ["imgs/myimage.png"]` to config params, which helps with SEO/OG stuff.

And to meta: `{{ with .Params.author }}<meta name="author" content="{{ . }}">{{ end }}`

Which doesn't solve the issue of no opengraph author name on posts. But at least now there's a plain ol' meta author, which seems like a step in the right direction. I still don't know how to get an OG author on posts, and it's late...

**Comment by tmswfrk** [comment]
So I basically have zero SEO experience, and I'm finding that a lot of the documentation online for it is either outdated or unclear as to best practices. I find it odd that Google has this magical algorithm, everyone wants to use it, but no one truly knows how to and are constantly guessing as to how to make their website ascend the Google ranks.

I personally would love to see something more standard built in to the config.toml file so that I don't have to create and manage my own meta layout, guessing along the way and hoping that all my parameters translate over correctly. As it is, I added a ld+json section somewhere on my page, but Google said that for whatever reason, my datePublished entry had a bad escape sequence in it.

I think given how much cool stuff is in this theme, it'd be awesome if we had some insight here in this config.toml level to give us newbies some basic framework to follow for generic SEO. I'm still learning it right now, so if I find out anything interesting, I'm willing to share, but I'm unfortunately still in the newbie phase!

**Comment by tmswfrk** [comment]
And @RyanTG hopefully I'm helping, but I did find some of this online that I have since added for my blog / posts section that seem related to what you were looking for (although maybe you've figured this out by now). From my current meta.html layout partial:
`
{{ if eq .Section "blog" }}
  {{ with.Params.author }} 
    <meta property="og:article:author" content="{{humanize . }}" />
    <meta property="article:author" content="{{humanize . }}" /> 
    <meta name="author" content="{{humanize . }}" /> 
  {{ end }}
{{ end }}
`

Again, since I don't know SEO, I'm not completely familiar with the open graph idea versus more traditional meta tags, so I'm not clear how much of these I actually need to add or if I'm simply contributing to the bloat.

**Comment by RyanTG** [comment]
Thanks - that snippet is close to what I had, but it's really helpful to see! 

I think the Open Graphic idea is all about sharing links. Like, if you share a link on twitter, facebook, slack, IM, etc, then it won't be merely a url, but will contain a thumbnail, description, and sometimes author name. So, it's really valuable to have this data filled in.

**Comment by pacollins** [comment]
I think after looking into it, it might be worthwhile to do a theme-level meta block.

**Comment by ghillert** [comment]
Thanks for the discussion here. I am new to Hugo and this theme. It looks like the images are are not populated either. Personally, I like to share some of my blog posts on Twitter/FB and having the image is very useful. Is there are work-around?

**Comment by pacollins** [comment]
We just need to do a custom meta template for the theme. The hold up now is
wanting someone with seo knowledge to chime, or have someone research what
is really needed in 2020.

**Comment by RyanTG** [comment]
SEO isn't rocket science :rocket:  It's just getting a couple fields populated - and we can figure it out easily by just viewing source on some well-funded websites.

I'm busy for the next few days, but if no one else has touched it, I think I can write up some best practices for us to go by just so we have clear steps for moving forward. I'm already most of the way there on my personal site (with images working, etc.).

**Comment by pacollins** [comment]
Not rocket science, but I'd rather get it right the first time. Haha

**Comment by RyanTG** [comment]
Open Graph tags 101 ([source](https://ahrefs.com/blog/open-graph-meta-tags/) & [source](https://www.freecodecamp.org/news/what-is-open-graph-and-how-can-i-use-it-for-my-website/) and a few others). What follows is a digest of a "best practices" post (just select bits of the article, lightly edited by me), with **bold** comments by me. 

I've co-ran a website for the last 10 years that has good SEO, and is very highly ranked in a niche market: https://pinballmap.com/
And I've managed all the SEO for it. I don't live and die this stuff, though. You just gotta check off the boxes... So here goes:

_Only four are required for Facebook (& twitter/linkedin/etc) to understand the basics of your page:_

### og:title
- 40 characters for mobile and 60 for desktop is roughly the sweet spot.
- Use the raw title. Don’t include branding (e.g., your site name).
- **Use post `title` from front matter, and include logic to fallback to site [title] from config**

Example: `<meta property="og:title" content="Open Graph Meta Tags: Everything You Need to Know" />`

### og:url

Example: `<meta property="og:url" content="https://ahrefs.com/blog/open-graph-meta-tags/" />`

### og:image

- Use custom images for “shareable” pages (e.g., homepage, articles, etc.). **Use the featured image for each post**
- Use your logo or any other branded image for the rest of your pages. **Include logic to fall back to the [image] from config if no featured image is present**
- Use images with a 1.91:1 ratio and minimum recommended dimensions of 1200x630 for optimal clarity across all devices. **eh... **
- **If we have any issues with this displaying well, we can explore also using these tags: og:image:width and og:image:height**

### og:description

- Keep it short and sweet. Facebook recommends 2–4 sentences, but that often truncates.
- **Use post description, and fall back to either [description] or [about] param from config. Thoughts on that? Personally, my [about] is a better candidate, but maybe that's just me**

Example: `<meta property="og:description" content="Learn about 13 features that set Ahrefs apart from the competition." />`

## Other, less crucial, tags

### og:type

- Use "article" for articles and "website" for the rest of your pages.
- Other common ones: "video", "profile", "music"
- More: https://ogp.me/#types
- **I'm not sure of the best approach for us. I don't think `type` in the front matter is an appropriate value to use. Nor `categories`. So we might need to include a separate front matter param in the archetype, like `ogtype`, and then fallback to using "website" if it's not filled in**

Additionally, if you use `og:type = article` then you should also include the following sub types:

article:published_time - datetime - When the article was first published. **`date` from front matter. And it should be humanized (or cleaned up another way)**
article:author - profile array - Writers of the article. **`author` tag from front matter**
article:section - string - A high-level section name. E.g. Technology **this would be the `type` param in the front matter... or `categories`?**
article:tag **this would be the `tag` param from the front matter**

Examples: `<meta property="og:type" content="article" />`
Sub-type of `og:type = video`: `<meta property='og:video' content='https://www.youtube.com/v/BQBjVr1iHH4' />`

### og:locale

- **Defaults to US. Might be important for this theme?**

### og:site_name

- **Not crucial, but seems good to have. Use [title] param from config**

# Debugging

https://developers.facebook.com/tools/debug/sharing/
https://cards-dev.twitter.com/validator
https://www.linkedin.com/post-inspector/inspect/

Full site audit: https://ahrefs.com/site-audit

**Comment by pacollins** [comment]
Awesome stuff @RyanTG. My schedule ramped up this week, but I can look at
it this Sunday. If someone wants to head up a PR, I'd be happy to assist.
If not, I will gladly make the PR.

**Comment by pacollins** [comment]
The PR I just made is by no means a final product, but something for everyone to test with to make sure everything is showing up right for you.

**Comment by RyanTG** [comment]
I will contribute to this branch this week. I know it's a work in progress at present. But I know how to build upon it.

**Comment by ghillert** [comment]
Any updates on this? Would be cool to have proper support for this. I tend to share blog posts via Twitter/Facebook on occasion :-)

**Comment by pacollins** [comment]
I am a teacher and in grad school (this is a hobby), so as you can imagine
I'm pretty busy. If someone wanted to take over this PR, they could.
Otherwise it could be a while.

**Comment by RyanTG** [comment]
I honestly think the current PR is in good shape! But I can try to review it and see what else is needed. If it was merged now, I think it gets the job done.

**Comment by pacollins** [comment]
Yeah, if you wouldn't mind reviewing it - I just really don't remember
where I was at with it. Lol

**Comment by ghillert** [comment]
I will take a closer look tomorrow. At a first glance it looks good! I noticed that the generated HTML is not super-clean, lots of whitespace in between elements but that might be separate issue ;-)

**Comment by ghillert** [comment]
Just left a comment on the PR. The title tag has some additional quotes. By the way you can validate the tags via:

* Twitter: https://cards-dev.twitter.com/validator
* Facebook: https://developers.facebook.com/tools/debug/

**Comment by ghillert** [comment]
LGTM - once the quotes are fixed, the PR works for me (Twitter plus Facebook)

**Comment by pacollins** [comment]
Merged.
