### ISSUE TITLE
Question: Is there an easy option to enable fingerprinting (cache-busting) of resources? 

### ISSUE THREAD

**Issue by ghillert** [pacollins/hugo-future-imperfect-slim#172]
I am still somewhat new to Hugo ad this awesome theme. I ran into some cache-busting issues. I saw some general pointers for Hugo e.g. the fingerprint pipe but that seemed to pertain mostly to JS/CSS resources but not for images. Is there an easy way to enable fingerprinting for not just theme-related images but also for images in content? (Markdown)

**Comment by pacollins** [comment]
I think you might be able to cache content images via [image processing](https://gohugo.io/content-management/image-processing/), but I have just begun to dabble in that for a personal site.

Would you mind linking your resources so I can investigate?

To answer you question though (if my lack of knowledge doesn't already), I do not think the theme currently supports this.

**Comment by ghillert** [comment]
I think this may be less of an issue for me now and may not be an issue for "static site generators" in general.

While you could generate cache busting hashes for images, css, js files etc., you would still run into issue for content files. In a dynamic app we would e.g. generate ETags and thus have potentially finer-grained control of the caching behavior ... But for static sites it is more of a server responsibility. For my use-case I fronted my Hugo site with Cloudflare and you can purge the cache there.

**Comment by pacollins** [comment]
In that case, I will assume your question has been answered. If not, feel free to reopen!
