### ISSUE TITLE
BUG: Categories didn't changed to Kategorie in PL language

### ISSUE THREAD

**Issue by PiotrWachulec** [pacollins/hugo-future-imperfect-slim#184]
# Bug Report

## Describe the bug

When I changed language to PL in the config file, the header **Categories** didn't changed to **Kategorie** on the sidebar.

## To Reproduce

1. Create new Hugo site with this theme
2. Set up polish language from the example configuration

## Expected behavior

When I changed the configuration to support polish language, the header should show 'Kategorie', not 'Categories'.

## Screenshots

![Zrzut ekranu z 2020-08-11 18-37-50](https://user-images.githubusercontent.com/11841233/89924108-d5e73980-dc01-11ea-9b98-f34b7ab4f5ab.png)

## Environment

 - **Hugo Version:** v0.74.3/extended
 - **Browser and Version:** Chrome 84.0.4147.105
 - **Platform:** Desktop/Ubuntu 18.04
 - **Link to Project:** [threelevelsdiary.wachulec.me](https://threelevelsdiary.wachulec.me)

## Additional context

None.

**Comment by pacollins** [comment]
That's an odd bug since it works with every other language. I'm not really sure how to approach it.

**Comment by PiotrWachulec** [comment]
Can I help you in some way? Do you need more explanation or additional reproduction steps or something other?

**Comment by pacollins** [comment]
I am able to reproduce it, I just can't think of _why_ it is happening. Your bug report is very clear, but every other language (which follow the same structure) works fine.

**Comment by PiotrWachulec** [comment]
@pacollins Any updates? :)

**Comment by pacollins** [comment]
I'm pretty swamped (I am a teacher in the US and we just went back, so with COVID its pretty chaotic). I really don't even know how to approach it.

**Comment by PiotrWachulec** [comment]
![Zrzut ekranu z 2020-08-18 14-51-57](https://user-images.githubusercontent.com/11841233/90515112-712c6180-e162-11ea-9420-ba589e32f563.png)
I founded that this issue is not only with the Polish language. In the others languages, it isn't correctly translated too. I checked it on the demo page.

**Comment by PiotrWachulec** [comment]
It is something related to singular and plural form of translations. When I commented 'one' line in categories parameter in pl.toml it started to work correctly. And when I do this in Reading time, there is the same effect. (Earlier in reading time I saw READING_TIME name instead of '1 minute...'.

**Comment by VincentTam** [comment]
> That's an odd bug since it works with every other language. I'm not really sure how to approach it.

@pacollins Sorry for late response.  The Polish language has more complicated plural rules than most other languages:
https://www.unicode.org/cldr/cldr-aux/charts/28/supplemental/language_plural_rules.html

To solve this, the appropriate keys `few` and `many` and their corresponding values has to be added to `i18n/pl.toml`.
