### ISSUE TITLE
BUG: Multilingual Search

### ISSUE THREAD

**Issue by WLun001** [pacollins/hugo-future-imperfect-slim#186]
# Bug Report

## Describe the bug

How to debug

always returns default language
at `main.js`
```js
  console.log("{{.Site.Language.Lang}}")
```

`index.json` always return default language content no matter what language i am at.

**Comment by pacollins** [comment]
Have you checked index.(lang).json on the root. I'm pretty suit that's the
path on Hugo.

**Comment by pacollins** [comment]
For Hugo, the language related file is located at `localhost:1313/{{langCode}}/index.json`. I do see this for French, can you confirm you see it for the language you need?

**Comment by WLun001** [comment]
@pacollins For `localhost:1313/{{langCode}}/index.json`, it returns the correct result. But when I look at network tab, it's always get from `localhost:1313/index.json`

Not sure if we can include langCode at the call
https://github.com/pacollins/hugo-future-imperfect-slim/blob/e1abfe88d1ae56da37977936c0994085486be8e6/assets/js/main.js#L63

**Comment by pacollins** [comment]
I believe this solves the problem, can you confirm? If so I will make a PR.

```
var lang = document.documentElement.lang;
var path;
if (lang == "{{ $.Site.Language }}") {
  path = "/index.json";
} else {
  path = "/"+lang+"/"+"index.json";
}
request.open("GET", path, true); // Request the JSON file created during build
```

**Comment by WLun001** [comment]
@pacollins thanks! that work.

**Comment by pacollins** [comment]
A bad habit of always using `$` to be safe. Haha
