### ISSUE TITLE
FEATURE: Headless CMS

### ISSUE THREAD

**Issue by stephenajulu** [pacollins/hugo-future-imperfect-slim#193]
# Feature Request

Headless CMS Integration

## Is your feature request related to a problem?

It would be great if it had a headless CMS because writing in markdown especially when working on a way to add nontechnical writers who have worked with wordpress before is frustrating. 

## Solution

Having a CMS makes writing easier and makes workflow efficient. All you have to do is write it in the CMS and post and you are done. I am looking to create a blog where different people will be writing and it would be good to have them write somewhere clean. Many of these people lack technical skills such as writing in markdown. Having something like [Forestry ](https://forestry.io)or [Netlify CMS](https://netlifycms.org) would really help provide a platform that doesn't require them to learn and write in Markdown.

A good solution is Netlify CMS

## Alternatives

An alternative is Forestry CMS

**Comment by pacollins** [comment]
I agree with, if someone takes this on, to use Netlify CMS.
