### ISSUE TITLE
BUG: Failed to find a valid digest in the 'integrity' attribute

### ISSUE THREAD

**Issue by AdamIsrael** [pacollins/hugo-future-imperfect-slim#195]
# Bug Report

## Describe the bug

The CSS fails to load when viewing the website, but works fine when viewed locally.

This error is in the console:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://www.adamisrael.com/css/bundle.min.d9e04ae08c9b3049b766dbd4aeab7d862c5ea1d13679b621490e0f5df5507497.css' with computed SHA-256 integrity '0bPSggDyz/8YuyOAVu2KVTdG7EysVeygZ+niczk1sIM='. The resource has been blocked.
```

## To Reproduce

1. Go to [adamisrael.com](http://adamisrael.com)
3. See page load without CSS

## Expected behavior

The CSS loads.

## Screenshots

![image](https://user-images.githubusercontent.com/125008/92183247-adb6b900-ee02-11ea-822f-ff28f1474f3a.png)

## Environment

 - **Hugo Version:** Hugo Static Site Generator v0.74.3-DA0437B4/extended linux/amd64 BuildDate: 2020-07-23T16:30:30Z 
 - **Browser and Version:** Chromium 86.0.4240.22
 - **Platform:** Desktop
 - **Link to Project:**

## Additional context

I tried the latest regular and extended Hugo versions, with the same result.

**Comment by pacollins** [comment]
Hmm... try deleting your resources folder and rebuild the site.

**Comment by AdamIsrael** [comment]
No change. I removed `public/` and `resources/` and rebuilt the site. I even deleted the site and pushed everything, to make sure I didn't have any old files lingering around.

**Comment by AdamIsrael** [comment]
I've just removed Cloudflare, to make sure that's not causing any issues. Pending DNS changes, so I'll re-test when they're propagated.

**Comment by pacollins** [comment]
I'll download a clean copy and see if I have the same issue.

**Comment by AdamIsrael** [comment]
Removing Cloudflare seems to have fixed the issue. Cloudflare was legacy, back before the site was powered by Hugo.

I'm not familiar enough with crossorigin and integrity to understand _why_ it fails with Cloudflare. The issue is resolved from my point of view, but maybe this is a larger issue that needs to be looked at?

**Comment by pacollins** [comment]
When I got a clean copy, it had no problems locally. I will close, but if you notice other issues, feel free to reopen.
