### ISSUE TITLE
QUESTION: Adding new or changing css

### ISSUE THREAD

**Issue by justindesilets** [pacollins/hugo-future-imperfect-slim#196]
First, thank you for all the great work on this theme. I am really enjoying it. I read through the documentation and found the `cssFiles` option in the `config.toml`. I saw that there was a `assets/css/dark.css` file but how I change to this or any other css file was not obvious to me. Could you please explain how I can select an alternate css file so I might modify the look of this theme?

**Comment by pacollins** [comment]
Currently, you need to make changes to [`add-on.css` at the root of your site](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/exampleSite/static/css/add-on.css). Once I get around to it, you will be able to replace larger chunks via SCSS. See #178 .

Let me know if you need any more assistance.

**Comment by justindesilets** [comment]
@pacollins, thank you for the quick answer. I will take this and try and find some time in the next week to dig into it. If I'm able to get the look I'm hoping for I'll try and document the process and css to share back up.
