### ISSUE TITLE
BUG: License Status

### ISSUE THREAD

**Issue by VeitSanner** [pacollins/hugo-future-imperfect-slim#197]
# Bug Report

## Describe the bug

`LICENSE.md` declares _Creative Commons Attribution 3.0 Unported_ as the license of the theme, whereas `theme.toml` declares _MIT_ as the license to be used.

Please clarify the license under which the theme is distributed.

**Comment by pacollins** [comment]
Not sure how that slipped through. Will fix. It is CC, not MIT.
