### ISSUE TITLE
FEATURE: Optionally remove 'recent posts' from sidebar

### ISSUE THREAD

**Issue by Hermsi1337** [pacollins/hugo-future-imperfect-slim#20]
# Feature Request
**Is your feature request related to a problem? Please describe.**
It would be great if it was possible to disable the 'RECENT POSTS'-box in the sidebar.
Yet it's always displayed, even if `params.sidebar.postAmount` is set to `0`.

**Describe the solution you'd like**
In my opinion it would be enough just setting the key `params.sidebar.postAmount` to `false`: 
```toml
  [params.sidebar]
    # Sets the number of recent posts to show in the sidebar. The default value is 5.
    postAmount          = false
```

That way it would be enough to simply add an `if` in the corresponding html-template `layouts/partials/site-sidebar.html`:
```html
{{ if .Site.Params.sidebar.postAmount }}
    <section id="recent-posts">
        <header>
            <h1>{{ i18n "recent_posts" }}</h1>
        </header>
        {{ range first (.Site.Params.sidebar.postAmount | default 5) (where .Site.Pages  "Type" "post") }}
        <article class="mini-post">
            <section>
                {{ .Render "featured" }}
            </section>
            <header>
                <h1><a href="{{ .RelPermalink }}">{{ .Title }}</a></h1>
                <time class="published" datetime="">{{ default (i18n "date_format") | .Date.Format }}</time>
            </header>
        </article>
        {{ end }}
        {{ if ge (len (where .Site.Pages "Type" "post")) (.Site.Params.sidebar.postAmount | default 5) }}
        <a href="{{ with .Site.Params.viewMorePostsLink }}{{ . | relLangURL }}{{ else }}{{ "post" | relLangURL }}{{ end }}" class="button">{{ i18n "see_more" }}</a>
        {{ end }}
    </section>
    {{ end }}
```

**Describe alternatives you've considered**
Actually none 🤣 

**Additional context**
What do you think?

**Comment by pacollins** [comment]
I think it makes sense. I don't have time right this moment to look at it, if someone wants to make a PR with it, that would be awesome.

**Comment by pacollins** [comment]
@Hermsi1337 - Do you think false is easier than just setting 0? I assume if someone puts it at 0 they are essentially meaning false and that would make more semantic sense.

**Comment by Hermsi1337** [comment]
@pacollins - You're right.. `0` sounds more reasonable. (=
