### ISSUE TITLE
BUG: Development banner visible on production websites, if scripts are disabled.

### ISSUE THREAD

**Issue by bobemoe** [pacollins/hugo-future-imperfect-slim#202]
# Bug Report

## Describe the bug

The development banner introduced by #154 is visible on production websites, if scripts are blocked.

## To Reproduce

1. Use a browser with "NoScript" or "uMatrix" or just JavaScript disabled.
2. Visit home page, e.g: https://themes.gohugo.io/theme/hugo-future-imperfect-slim/
3. See ``This message, related to the development of the theme, only displays on the localhost homepage to notify you of any important theme changes.`` ...

## Expected behavior

Clean home page is shown.

## Screenshots
![2020-10-26-230527_1659x919_scrot](https://user-images.githubusercontent.com/2304970/97237811-d2665600-17df-11eb-96c4-792f8f071629.png)

## Suggestion
Looks like it is included and visible on the page by default and then hidden with JS if not required.

May be better to not actually include it on the page at all and then inject it with JS if required. This would keep the page content a bit cleaner too.

**Comment by pacollins** [comment]
I agree with what you are saying and I'm not opposed to injecting it after. I am wondering if there is a Hugo function that could only build it if using the Hugo server.

**Comment by pacollins** [comment]
I have just come across a better way to do this and just need to implement it. [`.Site.IsServer`](https://gohugo.io/variables/site/). When I have a moment this evening, I will push it through.

**Comment by pacollins** [comment]
@bobemoe - Check that and see what you think.

**Comment by dariagrudzien** [comment]
@pacollins @bobemoe I've realized I can see the same issue. Tested this branch today and I think it solves the issue.

**Comment by pacollins** [comment]
#215 has been merged.
