### ISSUE TITLE
BUG: Failed to get JSON resource - API.instagram Bad request 

### ISSUE THREAD

**Issue by Hugo-prod** [pacollins/hugo-future-imperfect-slim#205]
# Bug Report
Hello :) 

## Describe the bug
When i run Hugo i get this error
```bash  
ERROR 2020/11/07 23:47:42 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Bad Request
```

## Screenshots

![image](https://user-images.githubusercontent.com/22305996/98452924-0e8ca580-2154-11eb-9f50-a4e5d39cfb8c.png)

## Environment

 - **Hugo Version:** Hugo Static Site Generator v0.77.0/extended linux/amd64 BuildDate: 2020-10-31T12:31:06Z

---  

In my case, no need Instagram, so i disable ERROR with `ignoreErrors = ["error-remote-getjson"]`
But how to repair this error properly ?

**Comment by pacollins** [comment]
This looks like a possible Hugo error. I'll investigate further.

**Comment by pedrohbraga** [comment]
Hi! I have also been getting the same error, which I have only been able to bypass by including `ignoreErrors            = ["error-remote-getjson"]` within the first part of the `config.toml` file.

```
Hugo Version: Hugo Static Site Generator v0.79.0/extended windows/amd64 BuildDate: unknown
```

**Comment by pacollins** [comment]
I will work on trying to reproduce this tonight.

**Comment by pacollins** [comment]
I was correct, [it is a Hugo issue](gohugoio/hugo#7866). Removing the Instagram short codes from the example site solve the problem.
