### ISSUE TITLE
Question - Favicon placement

### ISSUE THREAD

**Issue by dariagrudzien** [pacollins/hugo-future-imperfect-slim#206]
I'm embarrassed to admit that I can't figure out how to make a favicon work with this theme. Where should I add the file? What format should it have - `.ico` or `.svg` ? I feel like I've tried everything - I used https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml#paramsmeta to try and figure it out, but no luck.

**Comment by pacollins** [comment]
Honestly, this might be something we should fix on the template. Start by changing the version to `"2"`. Favicons are really persistent in the cache.

If that doesn't work, make sure you have used https://realfavicongenerator.net/ to generate your favicon and set the following:

```
favicon = true
svg = false // true if .svg, or false if .icon
faviconVersion = "2"
msColor = "#ffffff" // These are both for the tile color
iOSColor = "#ffffff"
```

Hope that helps.

**Comment by dariagrudzien** [comment]
@pacollins Thank you for the swift reply! And the placement of the favicon itself, is the template expecting it to be in the root directory, or in `static/` ?

**Comment by pacollins** [comment]
Static just places files at the root when compiled.

**Comment by pacollins** [comment]
I will assume that this solved your issue, feel free to reopen if needed.

**Comment by dariagrudzien** [comment]
@pacollins Reopening this as I still can't figure it out. I combed GitHub to find a project which successfully set the favicon and found https://github.com/robisetiapermadi/bytesician-hugo/blob/3f0257899a0919531a6b4cd92b222c7818469c98/config.toml#L36 I can see that the favicon is located in `static/` directly, named `favicon.ico`. 

So that's exactly what I set in my project, remembering to increment the version as you suggested https://github.com/cybermagnolia/cybermagnolia.com/blob/main/config.toml#L39

At this point I think I tried every combination to troubleshoot this:I tried this favicon in a different project using the `github.com/theNewDynamic/gohugo-theme-ananke` theme and it worked right away. I used a different favicon which work

**Comment by stefanman125** [comment]
For anyone who is still having this issue, this configuration seemed to work for me:
1. In your `config.toml`, make sure to have `favicon` set to `true`.
2. Place your favicon images into the directory: `/static/favicon` (some themes don't need the favicon directory, but this one does)
3. Name your favicon images `favicon-16x16.png` and `favicon-16x16.png` (you don't need both)
For example, if you have one favicon image, it should be here: `/static/favicon/favicon-32x32.png`
