### ISSUE TITLE
SEO Schema

### ISSUE THREAD

**Issue by msft-jasonparker** [pacollins/hugo-future-imperfect-slim#207]
I'd like to add a partial to my site using this theme for SEO purposes but I'm using this theme as a sub module to my repo. Should I copy the layouts from the theme dir or what's the right approach?

**Comment by pacollins** [comment]
Check out the [readme#non-development](
https://github.com/pacollins/hugo-future-imperfect-slim#non-development)

You should add `layouts/partials/head.html` to your root directory and it
will overwrite the theme's layout at the same location.

**Comment by pacollins** [comment]
I will assume that this solved your question, if not feel free to reply or reopen.
