### ISSUE TITLE
How do I add a new social in config.toml?

### ISSUE THREAD

**Issue by pratikjagrut** [pacollins/hugo-future-imperfect-slim#209]
I want to add link of my `dev.to` profile in social same as a Medium profile but I don't know how to do that can somebody help me here?

**Comment by martijnvandenboom** [comment]
The first thing I would recommend is to use a grep tool for your OS. I have done it in the past and figured out the changes needed to be made in multiple files... so it takes some searching to find the right references. Another tool I have used is the developer option in the browser. Is this helping you in the right way? If needed I can look into it again. You can let me know.

**Comment by pacollins** [comment]
#140 will show you how to do it. I was working on a new implementation but got busy.

**Comment by pacollins** [comment]
Closing, Feel free to reopen if issue persists.
