### ISSUE TITLE
How do I list blog old-blog-first fashion?

### ISSUE THREAD

**Issue by pratikjagrut** [pacollins/hugo-future-imperfect-slim#212]
I'm writing a tech blog series in which I want to list old blog first how do I do it?

**Comment by pacollins** [comment]
This functionality is not currently implemented unless there is a global Hugo parameter for the config. It would need a pull request implementing [`.Pages.ByDate.Reverse`](https://gohugo.io/templates/lists#reverse-order) as a `config.toml` param.

I am open to approving a PR for it, or you could adjust your own templates. 😄

**Comment by pacollins** [comment]
Closing, Feel free to reopen if issue persists.
