### ISSUE TITLE
Error at Say something below a blog item.

### ISSUE THREAD

**Issue by martijnvandenboom** [pacollins/hugo-future-imperfect-slim#213]
# Bug Report

## Describe the bug

The website gives an Error at Say something below a blog item.
Error: Sorry, there was an error with your submission. Please make sure all required fields have been completed and try again.

## To Reproduce

1. Go to your website. ;)
2. Open a blog item.
3. Scroll down to 'Say something'
4. Fill the form: name, website, email, message.
5. Pass the reCAPTCHA
6. Press Submit.
7. See error

Error: Sorry, there was an error with your submission. Please make sure all required fields have been completed and try again.

## Expected behavior

My expectation would be that a comment is placed below the blog item.

## Screenshots

<img width="910" alt="image" src="https://user-images.githubusercontent.com/64367423/102693693-b9e14d80-421c-11eb-82c2-3d73785742b5.png">

## Environment

 - **Hugo Version:** 0.79
 - **Browser and Version:** Safari: 14.0.2 (16610.3.7.1.9), Google Chrome: 87.0.4280.88 (Official Build) (x86_64)
 - **Platform:** iPad (iOS) en MacBook Pro (macOS)
 - **Link to Project:** https://github.com/pacollins/hugo-future-imperfect-slim.git

## Additional context

Can you reproduce this error?

**Comment by flawhoodlum1** [comment]
Flaw Hoodlum Entourage authorize

**Comment by pacollins** [comment]
I do not get this error on my site, which runs the current version of comments. Make sure that you have followed the [wiki for Staticman](https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml#paramsstaticman). If it is still not working, please let me know.

**Comment by pacollins** [comment]
Closing, Feel free to reopen if issue persists.
