### ISSUE TITLE
BUG: double slash in URL of demo site

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#230]
# Bug Report

## Describe the bug

When one clicks on any link in the landing page of the demo site, one would observe double slash in the address bar.

    https://themes.gohugo.io//theme/hugo-future-imperfect-slim/post/

## To Reproduce

1. Go to the [official demo site](https://themes.gohugo.io/theme/hugo-future-imperfect-slim/)
2. Click on any link that refer to somewhere on this site.
3. See the double slash

## Expected behavior

No double slash in the URL.

## Screenshots

![Screenshot from 2021-03-06 19-00-09](https://user-images.githubusercontent.com/5748535/110216221-30056000-7eae-11eb-9396-df585c709b73.png)

## Environment

 - **Hugo Version:** latest
 - **Browser and Version:** Opera 71
 - **Platform:** Desktop
 - **Link to Project:**

## Additional context

[Add any other context about the problem here.]

**Comment by pacollins** [comment]
Looks like Hugo is no longer building demo sites, so the problem is solved with https://hugo-future-imperfect-slim.netlify.app/
