### ISSUE TITLE
BUG: broken link highlight.js

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#236]
# Bug Report

## Describe the bug

The link to highlight.js is broken and it needs an update.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/fa6c8c0da163dd3ea19822b017464957053f5226/layouts/partials/scripts.html#L3

https://github.com/pacollins/hugo-future-imperfect-slim/blob/2693d913cd78a8453fc263f709f5ce15e8014f23/layouts/partials/head.html#L22

## To Reproduce

1. Enable `highlightjs` in `config.toml`.
2. Generate the site.
3. View the site in any modern web browser and open the web dev tool.
4. See error 404 in the Network tab in the web dev tool.

## Expected behavior

No 404 error shown

## Screenshots

![Screenshot from 2021-03-08 12-31-01](https://user-images.githubusercontent.com/5748535/110328641-e0dd3d80-801b-11eb-8e20-b29837495224.png)

## Environment

 - **Hugo Version:** latest
 - **Browser and Version:** Opera 71
 - **Platform:** Desktop
 - **Link to Project:** https://framagit.org/VincentTam/fish-demo

## Additional context

- related: #218 
- lib on cdnjs : https://cdnjs.com/libraries/highlight.js

**Comment by giom-mallet** [comment]
Hi， The baseURL should be : 
baseurl = "https://agirpourvous-shanghai.fr/"

I must mention that at the moment, this URL displays the site generated last year. The problem I meet is when I run hugo server. I didn't deploy online yet.

**Comment by pacollins** [comment]
@VincentTam - Did #239 not resolve this?

**Comment by pacollins** [comment]
Just tested locally and no longer have this error. Feel free to reopen if it is still an issue.
