### ISSUE TITLE
BUG: featuredpath other than 'date' resolves path to img/img/desired/path

### ISSUE THREAD

**Issue by serialc** [pacollins/hugo-future-imperfect-slim#24]
# Bug Report
In post parameters, the 'featuredpath' must use 'date' otherwise the url base will resolve to 'img/img/XXX' where 'XXX' is the alternative provided path. 

## To Reproduce
Create a new post.
Set `featuredpath: 'pictures/post941pics'`
Compile/hugo.
See resulting html path be to `/img/img/pictures/post941/theimage.png`

## Expected behavior
The resulting html path to be `/pictures/post941/theimage.png`
- where theimage.png is defined in 'featured'.

## Environment
 - **Hugo Version:** [e.g. 0.55.6]

**Comment by serialc** [comment]
Hmmm, looking at the code [here](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/post/featured.html) it looks to be like this by design... correct?

**Comment by pacollins** [comment]
Good catch, this is a bug from when I converted this. Will fix it now.

**Comment by pacollins** [comment]
New interaction will be
```
if (.Params.featuredpath = date) {
    var src = /img/YEAR/MONTH/.Params.featured
} else {
    var src = /img/.Params.featuredpath/.Params.featured
}
```
