### ISSUE TITLE
BUG: Manage the menu

### ISSUE THREAD

**Issue by giom-mallet** [pacollins/hugo-future-imperfect-slim#247]
# Bug Report

## Describe the bug

Hi, I keep meeting the same challenge when trying to workout a new menu item. I want to add a menu item called "events" but I can't make it show on the site top menu. 

## To Reproduce

1. I created a "evenements" subfolder in the content folder. 
2. I added 3 events pages. After building I can find them at https://mysite.fr/event/page
3. I added the following in the config.toml

  [[menu.main]]
    name              = "Evenements"
    identifier        = "evenements"
    url               = "/evenements/"
    pre               = "<i class='fas fa-calendar-check'></i>"
    weight            = 5

and 

    [[languages.fr.menu.main]]
      name              = "Évènements"
      identifier        = "evenements"
      url               = "/evenements/"
      pre               = "<i class='fas fa-calendar-check'></i>"
      weight            = 5

4. The new menu item doesn't display

## Environment

 - **Hugo Version:** [e.g. 0.46]
 - **Browser and Version:** [e.g. Chrome 74.0.3729.108]
 - **Platform:** [e.g. Desktop/Mobile]
 - **Link to Project:**

## Additional context

I am using the website in french only : 
in config.toml : 
 - disableLanguages        = ["en"]
 -     languageMenu        = false

**Comment by pacollins** [comment]
A link to your config file (or a pastebin link) would help diagnose.

**Comment by giom-mallet** [comment]
Hi @pacollins, thank you for your answer, sorry for the delay, I had to remove some credentials from the file .

Here it is :

[config - Copy.toml.txt](https://github.com/pacollins/hugo-future-imperfect-slim/files/6418683/config.-.Copy.toml.txt)

**Comment by VincentTam** [comment]
Hi @giom-mallet,

Related PR: #232.  I suggest removing slashes `/` in the `url`.

```sh
sed -i 's/url/\///g' config.toml
```

**Comment by giom-mallet** [comment]
Hi Vincent,

Sorry, I am not 100% clear, by what should I replace the "/" in the URL should they be escaped?

An example would be welcome

Thanks!

Guillaume Mallet
________________________________

**Comment by VincentTam** [comment]
Hi Guillaume,
Sorry, my mind blocked me when I was writing my previous message.  I wanted to represent the idea of "remove all slashes `/` at all lines containing `url`" with `sed` for fun.  Actually I did the job, so users just need to update this theme to include the latest PRs.

Sorry I messed up the order of the action `s/\///g` and the scope `/url/` in the above `sed` command.  I played with Zsh to get this right.

```sh
cat << EOF | sed '/url/s/\///g'
url = "/"
url = "/home/"
url = "/contacts/"
EOF
# → url = ""
# → url = "home"
# → url = "contacts"
```

**Comment by giom-mallet** [comment]
I spotted the issue. 
I had 'languages' instead of 'Languages' in the toml header
