### ISSUE TITLE
Type: Maintenance Is there any reason not to raise the version of Font Awesome?

### ISSUE THREAD

**Issue by orlea** [pacollins/hugo-future-imperfect-slim#26]
# Feature Request
I wanted to send a pull request to add the keybase and mastodon icons to social-icon.html.
But the icons I want to add are compatible only with Font Awesome v5.8 or higher.
Is there any reason not to use the higher version?
I tried v5.9.0 on examplePage, but the icons seem to be showing without problems.

**Comment by pacollins** [comment]
Just haven't got around to it yet. : ) Feel free to make a PR, or I can
later.

Thanks!
