### ISSUE TITLE
QUESTION: Make homepage /"Home"-link to static site 

### ISSUE THREAD

**Issue by zwogorg** [pacollins/hugo-future-imperfect-slim#261]
Hi, 

I'm new to hugo and this theme but I love it so far. But I have on question: 
Let's say my site's url is example.com. When I open example.com in a browser the startpage shows latest blog posts. I'd like this site to be a static welcome page, so that the blog posts are reachable via the "Blog"-menu.

How can I achieve this?

Greetings
zwog

**Comment by pacollins** [comment]
You would have to make it yourself at `YOURSITE/layouts/index.html`.

[`layouts/_default/single.html`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/_default/single.html) is what I would use to build it from.

Hope that helps get you started, feel free to keep commenting if you need more help!

**Comment by zwogorg** [comment]
Thanks, that was exactly the information I needed. It works now :)
