### ISSUE TITLE
QUESTION: Search function only works locally

### ISSUE THREAD

**Issue by wanderland-designs** [pacollins/hugo-future-imperfect-slim#264]
Hi, 

I'm new to hugo and I've been working with this theme for only a short while. I've been having the recurring issue that the search function only works locally when I use "hugo server" and not on my website. It simply will not react at all except for change the url with "/#search-input". Is this an issue with hugo itself or have I somehow set the files up wrong?
[Here is my website](https://ib-land.netlify.app/) if that helps. My repositories are private so I can share it as a collaborator if anyone needs to take a look at those as well.

**Comment by pacollins** [comment]
https://hugo-future-imperfect-slim.netlify.app/

That is an active build of the current `master` branch with search working properly. My suggestion would be to get the latest version of the theme and the latest version of Hugo-Extended.

**Comment by wanderland-designs** [comment]
That resolved it completely, didn't realize I was using an outdated version. Thanks a lot!
