### ISSUE TITLE
BUG: Incorrect Staticman v3 form URL

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#28]
The code for Staticman integration confuses me.

1. Should `{{ with ... }} ... {{ end }}` enclose the entire HTML form?
2. What does `/data` represent in Staticman's v3 URL scheme in eduardoboucas/staticman#219?  Even though I didn't tested the GitHub Apps functionality, which won't interest any evangelical free software users, AFAIK such theme remains valid.  The `/data` part probably needs to be removed.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/e0eb98282872a2e89e5f4654fc7f214b957d1fcd/layouts/post/staticman.html#L1-L28

**Comment by VincentTam** [comment]
For the first question, I've found the answer: the `with` captures `.Site.Params.staticman`.  This looks odd, but it's a convenient shorthand.  I shouldn't mess it up with `.UniqueID` below.  Therefore, this question can be dropped.  It remains the second problem, which can be solved by my PR.

**Comment by pacollins** [comment]
Data is a Hugo thing. See [Data Templates](https://gohugo.io/templates/data-templates/).

**Comment by VincentTam** [comment]
@pacollins So you can set it inside repo config instead of the POST URL.  See the linked Staticman PR.

**Comment by pacollins** [comment]
I'm still confused on what you mean? My understanding is Hugo expects it to be in the `data` folder, so why not hardcode it?

**Comment by VincentTam** [comment]
> I'm still confused on what you mean? My understanding is Hugo expects it to be in the `data` folder, so why not hardcode it?

To makes things clear, there're two config files:

1. site config file: `config.xxxx`
    - theme-specific
    - for sending form data
1. repo config file: `staticman.yml`
    - must be root-level, file name can't be changed
    - for receiving data from a Staticman API instance

To get comments into Hugo's `data/`, the right place is [`path`](https://staticman.net/docs/configuration#path) in the repo config file.

In the linked Staticman PR, it's writen that

> ### /entry endpoint
> 
> New URL pattern added:
> /v3/entry/:service/:username/:repository/:branch/:property

Here, `property` means every *unindented* line in the repo, as the top of the [official sample file](https://github.com/eduardoboucas/staticman/blob/2be29f73fa0688e02770b9f118288b6e0e617b01/staticman.sample.yml#L1-L5) suggests.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/e0eb98282872a2e89e5f4654fc7f214b957d1fcd/exampleSite/staticman.yml#L1-L10
