### ISSUE TITLE
FEATURE: Add a link to the demo site

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#30]
# Feature Request

## Is your feature request related to a problem?

I've to leave this search and google this theme to reach https://themes.gohugo.io/hugo-future-imperfect-slim/, which contains a link to the demo site.  This is quite inconvenient.

## Solution

Please add a link to the demo site at the top like https://github.com/daattali/beautiful-jekyll/.

**Comment by pacollins** [comment]
It is in the `readme`, but I agree it should be at the top. Doing that now.

**Comment by VincentTam** [comment]
Thanks for your edit.  My eyes got tired.
