### ISSUE TITLE
BUG: Incorrect image paths

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#32]
# Bug Report
## Describe the bug

I tried building a demo site for this theme on Framagit: https://vincenttam.frama.io/fish-demo/blog/creating-a-new-theme/ with

```toml
baseurl = "https://vincenttam.frama.io/fish-demo/"
```

in `config.toml`.  However, the images aren't rendered.  Rendered HTML shows

```html
<article class="mini-post">
      <section>
        
<a href="/fish-demo/blog/hugoisforlovers/" class="image featured">
  <img src="/img/2014/04/pic01.jpg" alt="Pic 1">
</a>


      </section>
      <header>
        <h1><a href="/fish-demo/blog/hugoisforlovers/">Getting Started with Hugo</a></h1>
        <time class="published" datetime="">April 2, 2014</time>
      </header>
    </article>
```

The `src` of the `<img>` is incorrect in case of GitHub/GitLab project pages.  I'm not an expert in web design/development.  You're going to be more proficient than me to fix this.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/e0eb98282872a2e89e5f4654fc7f214b957d1fcd/layouts/post/featured.html#L1-L5

Besides, I also get error on nav bar and page redirect after submitting Staticman comment.  The images in the posts have incorrect URL's.

## To Reproduce

1. Use this theme on a GitHub/GitLab project pages
4. See broken images

## Expected behavior

![Screenshot from 2019-07-04 13-26-34](https://user-images.githubusercontent.com/5748535/60663386-61b75f80-9e5f-11e9-88e6-c3cf0304e1bf.png)

## Screenshots

![Screenshot from 2019-07-04 13-23-12](https://user-images.githubusercontent.com/5748535/60663226-e5248100-9e5e-11e9-82b0-9d354372f54e.png)

## Environment

 - **Hugo Version:** 0.55.6
 - **Browser and Version:** Firefox 67.0.4 (64-bit)
 - **Platform:** Desktop
 - **Link to Project:** https://framagit.org/VincentTam/fish-demo

**Comment by pacollins** [comment]
That is an interesting bug I will have to look into. It is due to the URL being relative for multilingual, so I think Hugo might be parsing it odd? I'll check back.

**Comment by VincentTam** [comment]
Thanks for reply.  I should have said that the contents of the demo site are copied from `exampleSite` by

```sh
cp -r exampleSite/* LICENSE.md .
```

**Comment by pacollins** [comment]
On mobile, so I'm not certain on this, but I think this should solve it. 

```
<img src="{{ (path.Join "img" (cond (eq .Params.featuredpath "date") (.Page.Date.Format "2006/01") (.Params.featuredpath)) .Params.featured) | relurl }}" alt="{{ .Params.featuredalt }}">
```

https://gohugo.io/functions/relurl/
