### ISSUE TITLE
BUG: nav bar URL error

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#34]
# Bug Report
## Describe the bug

Nav bar links duplicate project slug in GitHub/GitLab project pages.

On demo site: https://vincenttam.frama.io/fish-demo/, I got

    https://vincenttam.frama.io/fish-demo/fish-demo/categories/
and so on.

## Expected behavior

https://vincenttam.frama.io/fish-demo/categories/

## Screenshots

![Screenshot from 2019-07-05 19-38-34](https://user-images.githubusercontent.com/5748535/60738173-b4774100-9f5d-11e9-996a-800290d5528d.png)

## Environment

 - **Hugo Version:** 0.55
 - **Browser and Version:** Firefox 67.xxx
 - **Platform:** Desktop
 - **Link to Project:** https://framagit.org/VincentTam/fish-demo

**Comment by pacollins** [comment]
This is probably an issue similar to #32 / #33 dealing with `baseurl`.

**Comment by VincentTam** [comment]
> This is probably an issue similar to #32 / #33 dealing with `baseurl`.

Agreed.  Despite my PR's on another Hugo theme Beautiful Hugo, I can't tell what's wrong with this. :thinking: 

https://github.com/pacollins/hugo-future-imperfect-slim/blob/88d64ffa0b17798de3c712b445b22c5eccd1e02c/layouts/partials/site-header.html#L22-L24

**Comment by pacollins** [comment]
After some experimenting, I am still lost. I have [posted](https://discourse.gohugo.io/t/rellangurl-is-duplicating-baseurl/19489) the the question on the hugo boards.

**Comment by pacollins** [comment]
So the issue is the leading slash in the config.toml:

`url = "about/"` is the syntax it wants (you could drop the trailing slash if you wanted to). I'm not sure that is an intended interaction.

**Comment by VincentTam** [comment]
Thanks this works!

**Comment by pacollins** [comment]
The issue I posted says that is as intended, so this can close.
