### ISSUE TITLE
BUG: qutebrowser display problem

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#35]
# Bug Report
## Describe the bug

A user reported this theme's resposive issue in #18, in which @pacollins has provided a link to https://www.pacollins.com/.  I've used Firefox 67.0.4 (64-bit) to browse it.  That works great!  However, the display for qutebrowser is strange.

## To Reproduce

Open https://www.pacollins.com/ with qutebrowser.

## Expected behavior

![Screenshot from 2019-07-05 19-56-42](https://user-images.githubusercontent.com/5748535/60738569-11bfc200-9f5f-11e9-9376-56e7eeb9bfdb.png)

## Screenshots

![Screenshot from 2019-07-05 19-56-49](https://user-images.githubusercontent.com/5748535/60738588-27cd8280-9f5f-11e9-9e31-4d74f1214b39.png)

## Environment

 - **Hugo Version:** ?
 - **Browser and Version:** qutebrowser
 - **Platform:** Desktop
 - **Link to Project:** ?

```
$ qutebrowser --version
qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.8
Qt: 5.9.5
PyQt: 5.10.1

sip: 4.19.7
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: Ubuntu 18.04.2 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/vin100/.cache/qutebrowser
config: /home/vin100/.config/qutebrowser
data: /home/vin100/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

**Comment by pacollins** [comment]
Does this browser support css-grid?

It is displaying the mobile site for the content.

**Comment by VincentTam** [comment]
Thanks for response.  Obviously not, so close.

![Uploading Screenshot from 2019-07-05 20-34-50.png…]()
