### ISSUE TITLE
FEATURE: Add tags to this repo

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#40]
# Feature Request

## Is your feature request related to a problem?

Show tags on the top of this repo, like https://github.com/onweru/hugo-swift-theme.  This helps this theme is stand out by searching [#staticman](https://github.com/search?q=%23staticman).

**Comment by pacollins** [comment]
Thanks for this.

I have added some tags, if you think we should add more, let me know.
