### ISSUE TITLE
Country logo

### ISSUE THREAD

**Issue by Anu-kriti** [pacollins/hugo-future-imperfect-slim#42]
I can see a country logo at the extreme top right of the main page? Any idea how to remove that or change that..

Also I am using disqus here - 

```
Disqus comments not available by default when the website is previewed locally.
comments powered by Disqus
```

not sure why these issue?

Also, I added some pictures in .md which works fine in preview but when I load it onto website, it doesnt show there

**Comment by pacollins** [comment]
To remove the country logo, remove the `[Languages]` section of the config, [here](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/exampleSite/config.toml#L141)

Disqus only works on live sites, as it says. This is not a theme issue.

**Comment by Anu-kriti** [comment]
Thanks Pacollins that worked.

what do you mean by live sites? that I must be doing it over a purchased domain, Currently I am using netlify.com to publish my website. 

One more doubt I have - the featured and featured path (https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/exampleSite/content/blog/creating-a-new-theme.md) we have- how can we add more than one pic in that?

**Comment by pacollins** [comment]
Disque won't activate until your site is live on the web. If you are running `hugo server` it won't work yet. The message you received tells you that it is working, but doesn't function unless active.

Currently, it only supports a single image. When we address #41 that might change.
