### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by ghost** [pacollins/hugo-future-imperfect-slim#47]
https://html5up.net/license

Your LICENSE file makes it appear as though the original theme from HTML5Up was licensed under Expat/X11 though it was not and all users of remixes of the actual license (linked above) must give credit as required by the licensor.

**Comment by VincentTam** [comment]
Hi @balibebas !  Thanks for raising this issue.  If there were a "good 1st issue", I would give that to you.  Since this is @pacollins's work, I've requested his review to my edit in LICENSE.md in the linked PR.

**Comment by balibebas** [comment]
Thanks for moving quickly on this.

**Comment by balibebas** [comment]
Please reopen this issue. While I saw a pull request was made I can see there are still licensing issues. It's important these are not passed on to users as they may not understand they are in breach of the license using this software as it stands, including the Hugo team displaying this work in the Hugo theme store.

Here is the full text of the license from HTML5 Up:
https://tldrlegal.com/license/creative-commons-attribution-(cc)#fulltext

Note the following in the _Termination_ section:

> This License and the rights granted hereunder will terminate automatically upon any breach by You of the terms of this License.

And please review the terms and restrictions of the license. These include, but are not limited to, adding a URI to the license and stating the author and the name of the original work on every webpage produced by this adaptation of an adaptation of an original work.

**Comment by VincentTam** [comment]
@balibebas Thanks for your feedback.  I'm current working on this, and I'm going make this available for your review once the footer "Powered by Hugo ... under CC BY SA 3.0" have been translated into the six languages supported by this theme.

**Comment by balibebas** [comment]
Once again, thank you for taking quick, unabashed action on this @VincentTam. I have also opened an issue in the upstream repo linking to this one as may have seen. 

Please note this is a temporary GH account. Please don't be surprised if I ghost soon. I started self-hosting my git stuff a year ago and deleted my primary GH account a few months back.

**Comment by VincentTam** [comment]
> If by original version you're referring to the non-slim adaptation of the original work the statement "they didn't so I don't have to" if a Tu Quoque fallacy. As it stands "original version" is not clear.

I appreciate your criitical thinking, even though I haven't got the time to revise my knowledge in this field.

> Please note this is a temporary GH account. Please don't be surprised if I ghost soon. I started self-hosting my git stuff a year ago and deleted my primary GH account a few months back.

Self-hosting is great.  Migrating to GitLab is, IMO, even better, if you don't need specific GitHub features like GitHub Apps.

**Comment by pacollins** [comment]
1. To prevent license conflicts, the MIT license should be replaced with the CC 3.0 License.
2. In actuality, the current license (that I admittedly merged quickly) actually attributes too much to the original creator. The only thing that is the same is purely the _design_ and small segments of code. I restructured the HTML _and_ the CSS. This is a derivative work where it was substantially changed "under the hood" while aesthetically similar.
3. Credit does _not_ have to be given, visibly, on the site itself per [Section 4 (b)](https://creativecommons.org/licenses/by/3.0/legalcode). The work itself, as it stands in GitHub, includes all the documents within a repository, so credit in the LICENSE does meet the requirement here.
> The credit required by this Section 4 (b) may be implemented in any reasonable manner; provided, however, that in the case of a Adaptation or Collection, at a minimum such credit will appear, if a credit for all contributing authors of the Adaptation or Collection appears, then as part of these credits and in a manner at least as prominent as the credits for the other contributing authors.
4. We do need to include the URI, which should exist in the license with everything else.

**Comment by VincentTam** [comment]
@pacollins Thanks for explanation.  Lemme take a look at your review to my PR.
