### ISSUE TITLE
BUG: Social Share Buttons inside post not working

### ISSUE THREAD

**Issue by atomfrede** [pacollins/hugo-future-imperfect-slim#5]
# Bug Report
## Describe the bug
The social share buttons are not working as expected. They don't have the url and the title of the post. It is just e.g. `https://twitter.com/share?url=&text=&`

## To Reproduce
Setup a hugo site with this theme and look at the details of a post.

## Expected behavior
The share link should contain the permalink and the title of the post.

## Environment
 - **Hugo Version:**  
 - **Browser and Version:** Firefox 66.04
 - **Platform:** Desktop and Mobile
 - **Link to Project: ** https://atomfrede.gitlab.io/  https://gitlab.com/atomfrede/atomfrede.gitlab.io

**Comment by atomfrede** [comment]
I have found a solution, but not sure if that is the correct way of doing it. It seems right now nowhere the scratch content in the social share template is set. In `content-single.html` I added 

```
{{ .Scratch.Set "Permalink" .Permalink }}
{{ .Scratch.Set "Title" .Title }}
{{ .Scratch.Set "Author" .Author }}
```
which then can be used within the social share buttons

**Comment by pacollins** [comment]
Can you check if this happens on the other pages as well?

The real solution might be to sneak it further up the page so we can use the share buttons for more than just articles.

**Comment by atomfrede** [comment]
Yes you're right when the share menu is active the scratch is of course empty when you are not inside an article. What would be your expectation when e.g. being on the front page for the sharing link and title? The main page for example (as there is no permalink for any article).

**Comment by pacollins** [comment]
Personally, my expectation would be that I could share from any page on the site. Thoughts?

**Comment by Jubijub** [comment]
if you fix this please also make sure it fetches the images as well ?
