### ISSUE TITLE
BUG: Left sidebar overlapping

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#53]
# Bug Report
## Describe the bug

See the animated screenshot below and the title above.

## To Reproduce

Increase the size of the site icon.

## Expected behavior

Recent posts section won't overlap with intro section no matter how large the icon is.

## Screenshots

![screenshot gif](https://user-images.githubusercontent.com/5748535/63039498-bcfb5980-bec3-11e9-8a56-21635021569d.gif)

## Environment

 - **Hugo Version:** 0.56
 - **Browser and Version:** Firefox 68.0.1
 - **Platform:** Desktop
 - **Link to Project:** https://vincenttam.frama.io/fish-demo/, https://framagit.org/vincenttam/fish-demo/

**Comment by pacollins** [comment]
This issue occurs when the width isn't set on the image in the `config`.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/exampleSite/config.toml#L70

The quick solution would be to add a fallback width to the template here:

https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/partials/site-intro.html#L2

```
<img src="{{ .src | relURL }}" class="{{ .shape }}" width="{{ if isset .width }}{{ .width }}{{ else }}100px{{ end }}" alt="{{ .alt }}" />
```

100px could be substituted with whatever we deem the most appropriate as a max width.

Thoughts? I am fine with putting this PR together.

**Comment by pacollins** [comment]
The other solution is to remove this line in the CSS. Honestly, can't remember what all it was doing.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/d80bfe573cb7f423be4fe861a1dd108aac3eef0e/static/css/main.scss#L880

**Comment by VincentTam** [comment]
Thanks for reply.  Lemme get back to this in an hour after finding the translations.

**Comment by VincentTam** [comment]
> The other solution is to remove this line in the CSS. Honestly, can't remember what all it was doing.
> 
> https://github.com/pacollins/hugo-future-imperfect-slim/blob/d80bfe573cb7f423be4fe861a1dd108aac3eef0e/static/css/main.scss#L896

Thanks for pointing me to this useful CSS property.  That's almost _the_ solution.  This right thing to do is to have a quick look at what this property actually does, say, at https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows.  By playing with the samples, you'll get a quick idea.  Now, get our hands dirty with a web developer tool.

![grid](https://user-images.githubusercontent.com/5748535/63087677-0cd53180-bf53-11e9-9c39-f088636e6e65.gif)
GIF screen capture using [`byzanz-record`](https://gitlab.gnome.org/Archive/byzanz)

The `#wrapper` with selected.  Then we play with the first number in the above CSS property by pressing :arrow_up: / :arrow_down: .  At this stage, the solution should be crystal clear.  Adding a PR for that.
