### ISSUE TITLE
BUG: Titles, Tags, or Categories with long words cause horizontal scrolling small-width devices.

### ISSUE THREAD

**Issue by rmbolger** [pacollins/hugo-future-imperfect-slim#54]
# Bug Report
## Describe the bug
I'm not sure if this is actually a bug or working as intended. I also apologize in advance if I use the wrong terminology for some things. Web dev is not my area of expertise.

When I create posts that contain Titles, Tags, or Categories that contain long words, the page gets rendered wider than the viewport(?) on devices with a relatively small width such as a phone. By long words, I mean something like `thisisalongwordwithnospaces`. Adding spaces or hyphens allows the words to wrap on those boundaries and the view renders normally again.

## To Reproduce

1. Create a new post that contains any or all of the following. The longer the word is, the more obvious the problem is.

* `title = "My Post WithASuperLongWordIsLong"`
* `categories = ["MySuperLongWordIsLong"]`
* `tags = ["mysuperlongwordislong"]`

2. Open the page on a phone or emulated iPhone 6/7/8 view in Chrome

## Expected behavior

For Categories and Tags, I'd probably prefer the words get cut off (clipped?) rather than cause the whole page to be rendered too wide and need horizontal scrolling. I have no idea how to make this happen though. I tried playing around with overflow-related CSS things in Chrome dev tools without much luck.

I'm not exactly sure what I'd prefer to happen for Titles. Is there a way to force the browser to wrap long words even if they don't have natural breaks like a hyphen?

## Environment

 - **Hugo Version:** 0.57.0
 - **Browser and Version:** Mobile Safari on iOS 12.4, Chrome 76.0.3809.100 emulating iPhone 6/7/8, 
 - **Platform:** Mobile
 - **Link to Project:**

**Comment by pacollins** [comment]
This is an issue I have noticed before, just haven't taken the time with.

Possible solutions include:
- Shrinking font/letter spacing
- Wrapping text
- Truncating text

I will experiment later to see what is the best aesthetic.

**Comment by VincentTam** [comment]
Maybe we can give [flexbox](https://www.w3schools.com/css/tryit.asp?filename=trycss3_flexbox_flex-wrap_nowrap8) a try.
https://github.com/pacollins/hugo-future-imperfect-slim/blob/64535832649fab584fb81d6391ad70e25e512515/static/css/main.scss#L1520-L1524
