### ISSUE TITLE
FEATURE: Remove references to third-party CDNs from site head

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#56]
# Feature Request

## Is your feature request related to a problem?

:disappointed_relieved: Our project has several references to external scripts.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/d36f8892421fe4bf831e8d1cfb8b1dd40b04fae9/layouts/partials/scripts.html#L8-L10

:warning: This practice is _not_ recommended by \@<span></span>onedrawingperday in the updated *Theme Submission Guidelines* in gohugoio/hugoThemes\#<span></span>668.

:pen: I avoid putting links here so that our project _won't_ be linked there.

## Solution

Download the minified scripts and store the local copies under `assets`/`static`.

## Additional Context

The aforementioned issue in https://github.com/gohugoio/hugoThemes.

**Comment by pacollins** [comment]
Additional solution might be include a `useCDN` param in the `config.toml` so that users can opt-in to the CDN, but also include assets.
