### ISSUE TITLE
BUG: staticman comments rendered even when config boolean is false

### ISSUE THREAD

**Issue by rmbolger** [pacollins/hugo-future-imperfect-slim#59]
# Bug Report
## Describe the bug

In config.toml when `disqusShortname = ""` in the root and `staticman = false` in the `[params.staticman]` section (which are the defaults in the example site), the staticman comments markup is still rendered by `layouts\post\comments.html`.

## To Reproduce

1. Create a new site based on the example site
2. Go to any blog post
3. Scroll to the bottom
4. See the "Say Something" and "Comments" markup

## Expected behavior

The "Say Something" and "Comments" markup should not be rendered when `staticman = false`.

## Environment

 - **Hugo Version:** 0.57.0
 - **Browser and Version:** Chrome 76.0.3809.100
 - **Platform:** Desktop

**Comment by VincentTam** [comment]
Closed via #60.
