### ISSUE TITLE
BUG: Folder structure in README lists files that do not exist in the repo.

### ISSUE THREAD

**Issue by twatzl** [pacollins/hugo-future-imperfect-slim#62]
# Bug Report
## Describe the bug
There seems to be some file structure in the README.md file which is no longer in the repo.

I was looking for the itemized files listed in the tree, but it seems they do no longer exist in the repo.

```
|   └── itemized
|       ├── item1.fr.md
|       ├── item1.md
|       ├── item1.pl.md
|       ├── item2.fr.md
|       ├── item2.md
|       ├── item2.pl.md
|       ├── item3.fr.md
|       ├── item3.md
|       ├── item3.pl.md
|       ├── item4.fr.md
|       ├── item4.md
|       └── item4.pl.md
```

**Comment by VincentTam** [comment]
@twatzl Nice catch !  There was an update in the file tree of `exampleSite` in the README and it was bundled with the deletion of `exampleSite/content/itemized` :file_folder: at 779a35396672e723e03f4e6c58eab9905da8b61a.  That happended several months before I became a collaborator, so perhaps only @pacollins can give you a reason for that.

**Comment by pacollins** [comment]
Was a feature that I dropped in the slim version but planned to bring back once everything settled down. We can remove it for now.
