### ISSUE TITLE
FEATURE: Is it possible to put a logo in the navbar header?

### ISSUE THREAD

**Issue by twatzl** [pacollins/hugo-future-imperfect-slim#64]
Hello,
I am trying to put a logo in the navbar where the title text goes (just like github does). Is there any way to do this other than hacking in the code?

I tried setting the following, but it seems the text does not get interpreted as html:
```
    navbarTitle         = "<img src='/img/logos/blog-logo.png'>"
```

Thanks

**Comment by VincentTam** [comment]
> I am trying to put a logo in the navbar where the title text goes (just like github does). Is there any way to do this other than hacking in the code?

@twatzl Thanks for your interest in our theme, whose [original theme](https://html5up.net/future-imperfect) doesn't include "a logo in the navbar".  So the logo is intended to be put inside the top left grid with `id="site-intro"` instead of `navbar`.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/18b6e9c3f4884e3c7cdbb23a04189895e874f690/layouts/partials/site-header.html#L6-L20

To render HTML code in a Hugo parameter/variable, pipe it to the [`safeHTML`](https://gohugo.io/functions/safehtml/) method.

```go
{{ .Site.Params.header.navbarTitle | safeHTML }}
```

See this paragraph in the linked Hugo docs.

> However, without the `safeHTML` function, html/template assumes `.Site.Copyright` to be unsafe and therefore escapes all HTML tags and renders the whole string as plain text:
>
> ```html
> <p>© 2015 Jane Doe.  &lt;a href=&#34;https://creativecommons.org/licenses by/4.0/&#34;&gt;Some rights reserved&lt;/a&gt;.</p>
> ```

Hence, the answer to your question is no.

**Comment by pacollins** [comment]
I agree with @VincentTam's assessment. 

Is there a reason you don't want the logo in the `site-intro`?

**Comment by twatzl** [comment]
Thanks @VincentTam. I quickly hacked it together and it works fine with a little extra css.

@pacollins Just asthaetic reasons. I want the logo to be shown even when scrolling and I think it fits nicer in the navbar than to the intro. It seems a bit odd that this is not possible given that many websites have that arrangement with the logo in the navbar.

Also I think the intro part seems to be more for presenting myself and not my logo.

**Comment by pacollins** [comment]
Fair enough. Must be a thin logo you have. 😄

**Comment by twatzl** [comment]
Well. I think it is pretty standard. 
Are there any particular reasons to not include the `safeHTML` decorator per default in the theme?

**Comment by VincentTam** [comment]
> Are there any particular reasons to not include the `safeHTML` decorator per default in the theme?

I didn't write the this line of code, but I think that we're expecting text there, so omitting `safeHTML` keeps the template simple.  You may override this to adapt to your needs.

**Comment by twatzl** [comment]
So in conclusion we can say: Logo in the navbar is possible, if you edit the small piece of code.
I think that's fair enough.

**Comment by pacollins** [comment]
Well, the css would need to be written to prevent eyesores, but yes. If
someone wants to do that PR, I'm fine with approving it.
