### ISSUE TITLE
PRIORITY: Hugo 0.57.0 Breaking Changes

### ISSUE THREAD

**Issue by pacollins** [pacollins/hugo-future-imperfect-slim#68]
# ⚠️ HUGO BREAKING CHANGE ⚠️

I was notified by gohugoio/hugoThemes/issues/682 that: 

> a great number of theme demos now display empty homepages and/or post lists that point to section lists (instead of individual posts).

This includes us. The changes are described in more detail here gohugoio/hugoThemes/issues/678

**Comment by pacollins** [comment]
I have tested a solution, but a bug that was fixed in 0.57.1 is still present for me. Exploring a solution [here](https://github.com/gohugoio/hugoThemes/issues/682#issuecomment-522202963)

**Comment by VincentTam** [comment]
Why not add a parameter in the site config?  Many developers have done this solve the problem.

```toml
mainSections = ["blog", "post"]
```
