### ISSUE TITLE
BUG: Staticman reCAPTCHA Error

### ISSUE THREAD

**Issue by pacollins** [pacollins/hugo-future-imperfect-slim#7]
# Bug Report
## Describe the bug

Staticman V2 was not working due to an issue with request limits. Was upgraded to v3 and now it has a reCAPTCHA error even when disabled.

## To Reproduce
1. Submit a comment via Staticman

## Expected behavior

Comment should successfully post
##Screenshots

## Environment
 - **Hugo Version:** 0.50
 - **Browser and Version:** 
 - **Platform:** 
 - **Link to Project: **

## Additional context

See eduardoboucas/staticman#243

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab.

You may see [my Staticman + Beautiful Jekyll + Framagit demo](https://vincenttam.frama.io/tempsite) ([source](https://framagit.org/VincentTam/tempsite)) for a working example of reCAPTCHA v2 with Staticman v3 URL scheme.  It's built yesterday in response to a similar issue https://github.com/einsteinpy/blog.einsteinpy.org/issues/356.

**Comment by VincentTam** [comment]
After implementing #31, I've tested the reCAPTCHA integration of your theme, and reCAPTCHA isn't showing.  The true cause of this error is the lack of a `g-recaptcha` tag in the `form` tag.  You may see [reCAPTCHA v2's doc](https://developers.google.com/recaptcha/docs/display) for this.  Here's the official example pasted here for your convenience.

```html
<html>
  <head>
    <title>reCAPTCHA demo: Simple page</title>
     <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  </head>
  <body>
    <form action="?" method="POST">
      <div class="g-recaptcha" data-sitekey="your_site_key"></div>
      <br/>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>
```

You may compare your code

https://github.com/pacollins/hugo-future-imperfect-slim/blob/e0eb98282872a2e89e5f4654fc7f214b957d1fcd/layouts/post/staticman.html#L1-L28

with that of [Beautiful Hugo](https://github.com/halogenica/beautifulhugo/blob/07f765675dab2b00ad39aa460118edff2f2d3fcd/layouts/partials/staticman-comments.html).

```html
<form class="js-form form" method="post" action="{{ .Site.Params.staticman.api }}">
  <input type="hidden" name="options[slug]" value="{{ replace .RelPermalink "/" "" }}">
  <input type="hidden" name="options[parent]" value="">

  {{ if .Site.Params.staticman.recaptcha }}
  <input type="hidden" name="options[reCaptcha][siteKey]" value="{{ .Site.Params.staticman.recaptcha.sitekey }}">
  <input type="hidden" name="options[reCaptcha][secret]"  value="{{ .Site.Params.staticman.recaptcha.secret }}">
  {{ end }}

  <fieldset>
  <div class="textfield">
    <textarea name="fields[comment]" type="text" placeholder="{{ i18n "useMarkdown" }}"></textarea>
  </div>
  </fieldset>
  <!-- skipped fieldsets -->

  {{ if .Site.Params.staticman.recaptcha }}
  <fieldset>
    <div class="g-recaptcha" data-sitekey="{{ .Site.Params.staticman.recaptcha.sitekey }}"></div>
  </fieldset>
  {{ end }}

  <fieldset>
    <button class="button">
      Submit
    </button>
  </fieldset>
</form>
</section>
```

**Comment by VincentTam** [comment]
Pleaes forget my previous comment.  It seems the cause is

"The resource from “https://www.google.com/recaptcha/api.js?render=6Lcv8G8UAAAAAEqV1Y-XEPum00C_DxhD6O--qkFo” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)."

from my Firefox browser.

**Comment by VincentTam** [comment]
Related issue: https://github.com/eduardoboucas/staticman/issues/223

**Comment by VincentTam** [comment]
Update: Looking at Staticman's PRs, I've found an attempt to support reCAPTCHA v3 with Staticman.  Unluckily, it's mixed with lots of changes and it was closed.  I've made eduardoboucas/staticman#413 for that.
