### ISSUE TITLE
BUG: Missing locales for 404 page

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#70]
# Bug Report
## Describe the bug

https://github.com/pacollins/hugo-future-imperfect-slim/blob/58c2de987481f7bb3d3d37500186c69db633efe8/layouts/404.html#L56-L59

Since our theme claims to be a "multilingual blogging theme for Hugo", we've to fix that.

## Expected behavior

Translations for these strings.

**Comment by pacollins** [comment]
The translations exist in the i18n files, but I switched `404` pages and never hooked it back up.

**Comment by VincentTam** [comment]
Thanks for response.  Excuse me for overlooking the 404 keys in i18n/*.toml.
