### ISSUE TITLE
FEATURE: Search

### ISSUE THREAD

**Issue by pacollins** [pacollins/hugo-future-imperfect-slim#86]
# Feature Request

The framework of this exists in the theme, but it needs to be re-implemented. Previously it was a custom Google search. I would like to see some sort of internal static search.

**Comment by paleomariomm** [comment]
Dear @pacollins , I cannot see the Search area in the web. I checked in the `config.toml` that `searchMenu` is set to `true`, but cannot see anything. Any idea?

**Comment by pacollins** [comment]
@paleomariomm - This is an issue to implement it. The feature is not currently active.

**Comment by paleomariomm** [comment]
Thanks for the answer. When are you planning to implement it? I am currently reorganizing my entire web by using your theme (now it is in WP, vivaelsoftwarelibre.com), and this is a very important feature. Anyway, thanks for your work.

**Comment by pacollins** [comment]
If I am being honest, I am not sure. I wouldn't possibly have time until June at the earliest.

**Comment by pacollins** [comment]
@paleomariomm - Update: I currently have the search functionality implemented. Working on the front-end.

**Comment by pacollins** [comment]
Desktop version is fully functioning. Will complete mobile version tomorrow and create PR. 🎉 

![image](https://user-images.githubusercontent.com/11359433/82522562-d509a480-9af7-11ea-804e-b82f0ff80204.png)

**Comment by sopelt** [comment]
@pacollins , you are probably aware but there seems to be an issue with relative deployments and loading the search index:

![image](https://user-images.githubusercontent.com/738714/83717286-a7ae1200-a632-11ea-8691-61f3dcdf0f55.png)

Thank you for your work and this great theme!

**Comment by pacollins** [comment]
@sopelt - It does. I just downloaded a fresh version of the theme using the example site.

Make sure you make the changes listed at the top of #143. If I were to guess, this is the one you are missing from the config file:

...
disableLanguages = [""]

[outputs]
    home = ["html", "json"]

[params]
...

Also, closing this because the feature is up. I'm just a dolt who didn't link it right.

**Comment by pacollins** [comment]
@sopelt I just realized that. Thanks for making me aware. I'll look at it. The demo site has been the bane of my existence due to the post images and now this. Haha.
