### ISSUE TITLE
BUG: Incorrect german date format

### ISSUE THREAD

**Issue by th1l6f** [pacollins/hugo-future-imperfect-slim#89]
# Bug Report
## Describe the bug
The date_format in `i18n/de.toml` defined as ´02-01-2006´.  The common format in Germany is "02.01.2006", according to DIN 1355-1. Actually nowadays there's ISO 8601 - but this is not used in Germany. "02.01.2006" is the format you see in common software like Windows. This format is used by public authorities, too.

## Environment

 - **Hugo Version:** 0.57.2

**Comment by VincentTam** [comment]
Closed via #90.
