### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Danr17** [pacollins/hugo-future-imperfect-slim#9]
# Bug Report
## Describe the bug
Error parsing the template

## To Reproduce
hugo_0.55.6\hugo.exe server
Error: "C:\Users\.......\themes\hugo-future-imperfect-slim\layouts\partials\scripts.html:3:1": parse failed: template: partials/scripts.html:3: function "Site" not defined

**Comment by pacollins** [comment]
My fault for trying to push a fix quick last time. Updated now.
