### ISSUE TITLE
BUG: pagination button size on long titles

### ISSUE THREAD

**Issue by th1l6f** [pacollins/hugo-future-imperfect-slim#91]
# Bug Report
## Describe the bug
The buttons to navigate to the next or previous article are designed for quite short titles. Longer titles get wrapped. In this case, the border is to small. 

![now](https://user-images.githubusercontent.com/54466262/63954567-9ae90600-ca83-11e9-9e1a-b89d5b153f4e.png)

In my opinion, you can fix it by allowing the box to grow:
Currently, the css class button contains "`height: 4.8125em;`" . By switching to "`min-height: 4.8125em;`" the box can grow. I think, for usability, that's good solution.
![min-height](https://user-images.githubusercontent.com/54466262/63954677-c0760f80-ca83-11e9-9fcd-633cabe102c8.png)

A second way would be to cut the text. This could be done by adding these attributes to button:
```
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
```

From a designers point of view, this is probably preferable. Even better would be to cut the title and keep the ">". 

![overflow-hidden](https://user-images.githubusercontent.com/54466262/63954733-dbe11a80-ca83-11e9-86f3-4ed35ddd8a32.png)

## Environment

 - **Hugo Version:** v0.57.2
 - **Browser and Version:** Firefox 68, Chrome 76
 - **Platform:** Dektop

**Comment by VincentTam** [comment]
For desktop version, I prefer keeping a (truncated) title; for mobile version, :arrow_forward: and :arrow_backward: take less horizontal space.
