### ISSUE TITLE
BUG: Author not rendering in email link in share-buttons.html

### ISSUE THREAD

**Issue by djs-zmtc** [pacollins/hugo-future-imperfect-slim#95]
# Bug Report
## Describe the bug
When clicking on the 'email' share button, the link created puts the text '{     map[]}' in the subject line instead of the author name.

## Fix
Modify 'layouts/partials/head.html' and change

`{{ .Scratch.Set "Author" .Author }}`

to

`{{ .Scratch.Set "Author" .Params.Author }}`

Sorry -- not very proficient with git or pull requests (yet), so offered the above fix.

## To Reproduce
Create/open a post and click on the share email icon.

The link created will have the correct permalink, but the bogus author name.

## Expected behavior
The author name properly appearing in the email link.

## Screenshots
None

## Environment

 - **Hugo Version:** 0.58
 - **Browser and Version:** Chrome 77.0.3865.90
 - **Platform:** Desktop
 - **Link to Project:** (in development)

**Comment by pacollins** [comment]
Good catch. Will get to this soon.
