### ISSUE TITLE
FEATURE: Add Tags page similar to Categories page...

### ISSUE THREAD

**Issue by yndrelbosch** [pacollins/hugo-future-imperfect-slim#96]
# Feature Request

## Is your feature request related to a problem?

I'm wanting to add a tags page similar to the categories page already included, but can't figure out how to...

## Solution

Please add a tags page that will list all tags used in posts, and link to them.

**Comment by pacollins** [comment]
See #10 

Just as a heads up, both of the main maintainers of this theme just got back to work this fall and are swamped. We are still facilitating PRs from contributors, but our personal contributions are slim at the moment.

**Comment by pacollins** [comment]
This page exists under the same naming as categories. See (taxonomy templates](https://github.com/pacollins/hugo-future-imperfect-slim/tree/master/layouts/taxonomy).
